name = "rightathome-api"
main = "worker.js"
compatibility_date = "2023-12-01"

[env.production]
name = "rightathome-api"
route = { pattern = "rightathome-api.bmcii1976.workers.dev/*", zone_id = "your-zone-id" }

[vars]
WEATHER_API_KEY = "77b5b040303a47a1a3953924252803"

[triggers]
crons = []

[[routes]]
pattern = "rightathome-api.bmcii1976.workers.dev/*"