import { db } from "./index";
import { accounts } from "./schema";

interface AccountSeed {
  code: string;
  name: string;
  type: "asset" | "liability" | "equity" | "revenue" | "expense";
  subType: string | null;
  normalBalance: "debit" | "credit";
  description: string;
  isActive: boolean;
  parentCode: string | null;
}

const chartOfAccounts: AccountSeed[] = [
  // ── ASSETS ──────────────────────────────────────────────────────────────────
  {
    code: "1000",
    name: "Cash",
    type: "asset",
    subType: "current_asset",
    normalBalance: "debit",
    description: "Cash on hand and in registers",
    isActive: true,
    parentCode: null,
  },
  {
    code: "1010",
    name: "Checking Account",
    type: "asset",
    subType: "current_asset",
    normalBalance: "debit",
    description: "Primary business checking account",
    isActive: true,
    parentCode: "1000",
  },
  {
    code: "1020",
    name: "Savings Account",
    type: "asset",
    subType: "current_asset",
    normalBalance: "debit",
    description: "Business savings and reserve account",
    isActive: true,
    parentCode: "1000",
  },
  {
    code: "1100",
    name: "Accounts Receivable",
    type: "asset",
    subType: "current_asset",
    normalBalance: "debit",
    description: "Amounts owed by guests and partners",
    isActive: true,
    parentCode: null,
  },
  {
    code: "1200",
    name: "Prepaid Expenses",
    type: "asset",
    subType: "current_asset",
    normalBalance: "debit",
    description: "Expenses paid in advance (insurance, subscriptions)",
    isActive: true,
    parentCode: null,
  },
  {
    code: "1300",
    name: "Security Deposits Held",
    type: "asset",
    subType: "current_asset",
    normalBalance: "debit",
    description: "Security deposits held in trust for guests",
    isActive: true,
    parentCode: null,
  },
  {
    code: "1500",
    name: "Property & Equipment",
    type: "asset",
    subType: "fixed_asset",
    normalBalance: "debit",
    description: "Furniture, appliances, fixtures, and equipment",
    isActive: true,
    parentCode: null,
  },
  {
    code: "1510",
    name: "Accumulated Depreciation",
    type: "asset",
    subType: "contra_asset",
    normalBalance: "credit",
    description: "Accumulated depreciation on property and equipment",
    isActive: true,
    parentCode: "1500",
  },

  // ── LIABILITIES ─────────────────────────────────────────────────────────────
  {
    code: "2000",
    name: "Accounts Payable",
    type: "liability",
    subType: "current_liability",
    normalBalance: "credit",
    description: "Amounts owed to vendors and suppliers",
    isActive: true,
    parentCode: null,
  },
  {
    code: "2100",
    name: "Credit Card Payable",
    type: "liability",
    subType: "current_liability",
    normalBalance: "credit",
    description: "Outstanding credit card balances",
    isActive: true,
    parentCode: null,
  },
  {
    code: "2200",
    name: "Payroll Taxes Payable",
    type: "liability",
    subType: "current_liability",
    normalBalance: "credit",
    description: "Aggregate payroll tax liability (parent account)",
    isActive: true,
    parentCode: null,
  },
  {
    code: "2210",
    name: "Federal Income Tax Payable",
    type: "liability",
    subType: "current_liability",
    normalBalance: "credit",
    description: "Employee federal income tax withheld, pending remittance",
    isActive: true,
    parentCode: "2200",
  },
  {
    code: "2220",
    name: "Social Security Payable",
    type: "liability",
    subType: "current_liability",
    normalBalance: "credit",
    description:
      "Employee and employer Social Security tax pending remittance",
    isActive: true,
    parentCode: "2200",
  },
  {
    code: "2230",
    name: "Medicare Payable",
    type: "liability",
    subType: "current_liability",
    normalBalance: "credit",
    description: "Employee and employer Medicare tax pending remittance",
    isActive: true,
    parentCode: "2200",
  },
  {
    code: "2240",
    name: "FUTA Payable",
    type: "liability",
    subType: "current_liability",
    normalBalance: "credit",
    description: "Federal Unemployment Tax Act liability",
    isActive: true,
    parentCode: "2200",
  },
  {
    code: "2250",
    name: "SUTA Payable",
    type: "liability",
    subType: "current_liability",
    normalBalance: "credit",
    description: "State Unemployment Tax Act liability (Texas TWC)",
    isActive: true,
    parentCode: "2200",
  },
  {
    code: "2300",
    name: "Occupancy Tax Payable",
    type: "liability",
    subType: "current_liability",
    normalBalance: "credit",
    description:
      "Hotel occupancy tax collected, pending remittance to City/County/State",
    isActive: true,
    parentCode: null,
  },
  {
    code: "2400",
    name: "Security Deposits Liability",
    type: "liability",
    subType: "current_liability",
    normalBalance: "credit",
    description: "Liability for guest security deposits to be returned",
    isActive: true,
    parentCode: null,
  },
  {
    code: "2500",
    name: "Deferred Revenue",
    type: "liability",
    subType: "current_liability",
    normalBalance: "credit",
    description:
      "Advance payments from guests for future stays not yet earned",
    isActive: true,
    parentCode: null,
  },

  // ── EQUITY ──────────────────────────────────────────────────────────────────
  {
    code: "3000",
    name: "Owner's Equity",
    type: "equity",
    subType: "owners_equity",
    normalBalance: "credit",
    description: "Owner's capital contributions",
    isActive: true,
    parentCode: null,
  },
  {
    code: "3100",
    name: "Retained Earnings",
    type: "equity",
    subType: "retained_earnings",
    normalBalance: "credit",
    description: "Accumulated net income retained in the business",
    isActive: true,
    parentCode: null,
  },
  {
    code: "3200",
    name: "Owner's Draw",
    type: "equity",
    subType: "contra_equity",
    normalBalance: "debit",
    description: "Owner withdrawals from the business",
    isActive: true,
    parentCode: null,
  },

  // ── REVENUE ─────────────────────────────────────────────────────────────────
  {
    code: "4000",
    name: "Rental Revenue",
    type: "revenue",
    subType: "operating_revenue",
    normalBalance: "credit",
    description: "Nightly rental income from guest stays",
    isActive: true,
    parentCode: null,
  },
  {
    code: "4010",
    name: "Cleaning Fee Revenue",
    type: "revenue",
    subType: "operating_revenue",
    normalBalance: "credit",
    description: "Cleaning fees charged to guests",
    isActive: true,
    parentCode: null,
  },
  {
    code: "4020",
    name: "Pet Fee Revenue",
    type: "revenue",
    subType: "operating_revenue",
    normalBalance: "credit",
    description: "Pet fees charged to guests with animals",
    isActive: true,
    parentCode: null,
  },
  {
    code: "4030",
    name: "Late Checkout Revenue",
    type: "revenue",
    subType: "operating_revenue",
    normalBalance: "credit",
    description: "Fees charged for late checkout requests",
    isActive: true,
    parentCode: null,
  },
  {
    code: "4040",
    name: "Upsell Revenue",
    type: "revenue",
    subType: "operating_revenue",
    normalBalance: "credit",
    description: "Revenue from upsells (early check-in, amenity bundles, etc.)",
    isActive: true,
    parentCode: null,
  },
  {
    code: "4100",
    name: "Platform Commission Offset",
    type: "revenue",
    subType: "contra_revenue",
    normalBalance: "debit",
    description:
      "Contra-revenue for Airbnb/VRBO host-side commission deductions",
    isActive: true,
    parentCode: null,
  },

  // ── EXPENSES ────────────────────────────────────────────────────────────────
  {
    code: "5000",
    name: "Cleaning Supplies",
    type: "expense",
    subType: "cost_of_revenue",
    normalBalance: "debit",
    description:
      "Cleaning chemicals, trash bags, paper products, and disposables",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5010",
    name: "Cleaning Labor",
    type: "expense",
    subType: "cost_of_revenue",
    normalBalance: "debit",
    description: "Labor cost for turnover and deep cleaning services",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5020",
    name: "Laundry Expense",
    type: "expense",
    subType: "cost_of_revenue",
    normalBalance: "debit",
    description: "Laundry service, linens, towels, and washing supplies",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5100",
    name: "Maintenance Supplies",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description: "Hardware, tools, paint, lightbulbs, and repair materials",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5110",
    name: "Maintenance Labor",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description: "Labor cost for maintenance and repair work",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5200",
    name: "Lawn Care Expense",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description: "Lawn mowing, landscaping, irrigation, and yard maintenance",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5210",
    name: "Pool Maintenance",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description: "Pool chemicals, cleaning, equipment, and service",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5300",
    name: "Utilities - Electric",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description: "Electricity charges for rental properties",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5310",
    name: "Utilities - Water",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description: "Water and sewer charges for rental properties",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5320",
    name: "Utilities - Gas",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description: "Natural gas charges for rental properties",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5330",
    name: "Utilities - Internet/Cable",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description: "Internet and cable service for rental properties",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5400",
    name: "Insurance",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description:
      "Property insurance, liability insurance, and umbrella policies",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5500",
    name: "Property Tax",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description: "Annual property tax assessments",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5600",
    name: "Depreciation Expense",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description: "Depreciation of furniture, fixtures, and equipment",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5700",
    name: "Marketing & Advertising",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description:
      "Google Ads, social media advertising, professional photography",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5800",
    name: "Platform Fees",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description: "Airbnb, VRBO, and other platform service fees and commissions",
    isActive: true,
    parentCode: null,
  },
  {
    code: "5900",
    name: "Office Supplies",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description: "Printer paper, toner, stationery, and office consumables",
    isActive: true,
    parentCode: null,
  },
  {
    code: "6000",
    name: "Payroll Expense - Wages",
    type: "expense",
    subType: "payroll_expense",
    normalBalance: "debit",
    description: "Gross wages paid to employees",
    isActive: true,
    parentCode: null,
  },
  {
    code: "6010",
    name: "Payroll Expense - Employer SS",
    type: "expense",
    subType: "payroll_expense",
    normalBalance: "debit",
    description: "Employer's share of Social Security tax (6.2%)",
    isActive: true,
    parentCode: null,
  },
  {
    code: "6020",
    name: "Payroll Expense - Employer Medicare",
    type: "expense",
    subType: "payroll_expense",
    normalBalance: "debit",
    description: "Employer's share of Medicare tax (1.45%)",
    isActive: true,
    parentCode: null,
  },
  {
    code: "6030",
    name: "Payroll Expense - FUTA",
    type: "expense",
    subType: "payroll_expense",
    normalBalance: "debit",
    description:
      "Federal Unemployment Tax Act employer expense (0.6% after credit)",
    isActive: true,
    parentCode: null,
  },
  {
    code: "6040",
    name: "Payroll Expense - SUTA",
    type: "expense",
    subType: "payroll_expense",
    normalBalance: "debit",
    description: "State Unemployment Tax Act employer expense (Texas TWC rate)",
    isActive: true,
    parentCode: null,
  },
  {
    code: "6100",
    name: "Website Hosting",
    type: "expense",
    subType: "technology_expense",
    normalBalance: "debit",
    description: "Vercel, Cloudflare, and hosting infrastructure costs",
    isActive: true,
    parentCode: null,
  },
  {
    code: "6110",
    name: "API Costs",
    type: "expense",
    subType: "technology_expense",
    normalBalance: "debit",
    description: "Third-party API usage fees (AI, SMS, email, etc.)",
    isActive: true,
    parentCode: null,
  },
  {
    code: "6120",
    name: "Domain & SSL",
    type: "expense",
    subType: "technology_expense",
    normalBalance: "debit",
    description: "Domain registration, renewal, and SSL certificate costs",
    isActive: true,
    parentCode: null,
  },
  {
    code: "6130",
    name: "SaaS Subscriptions",
    type: "expense",
    subType: "technology_expense",
    normalBalance: "debit",
    description:
      "Software subscriptions (PMS, channel manager, accounting, etc.)",
    isActive: true,
    parentCode: null,
  },
  {
    code: "6200",
    name: "Stripe Processing Fees",
    type: "expense",
    subType: "financial_expense",
    normalBalance: "debit",
    description: "Stripe payment processing fees (2.9% + $0.30)",
    isActive: true,
    parentCode: null,
  },
  {
    code: "6210",
    name: "PayPal Processing Fees",
    type: "expense",
    subType: "financial_expense",
    normalBalance: "debit",
    description: "PayPal payment processing fees",
    isActive: true,
    parentCode: null,
  },
  {
    code: "6300",
    name: "Professional Services",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description: "Accounting, legal, consulting, and professional fees",
    isActive: true,
    parentCode: null,
  },
  {
    code: "6400",
    name: "Travel & Transportation",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description: "Mileage, fuel, and travel between properties",
    isActive: true,
    parentCode: null,
  },
  {
    code: "6500",
    name: "Miscellaneous Expense",
    type: "expense",
    subType: "operating_expense",
    normalBalance: "debit",
    description: "Expenses that do not fit other categories",
    isActive: true,
    parentCode: null,
  },
];

async function seed() {
  console.log("Seeding chart of accounts...");

  // Insert all accounts. Using onConflictDoNothing so re-running is safe.
  for (const acct of chartOfAccounts) {
    await db
      .insert(accounts)
      .values({
        code: acct.code,
        name: acct.name,
        type: acct.type,
        subType: acct.subType,
        normalBalance: acct.normalBalance,
        description: acct.description,
        isActive: acct.isActive,
        parentCode: acct.parentCode,
      })
      .onConflictDoNothing({ target: accounts.code });
  }

  console.log(
    `Seeded ${chartOfAccounts.length} accounts in the chart of accounts.`
  );
}

seed()
  .then(() => {
    console.log("Seed complete.");
    process.exit(0);
  })
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  });
