/**
 * Property photo manifest - auto-generated from disk scan + AI classification
 * Maps property slugs to their photo files with categories
 */

export interface PropertyPhotoEntry {
  filename: string;
  category: string;
  url: string;
  alt: string;
}

interface PhotoDef {
  f: string;  // filename
  c: string;  // category
  u: string;  // url
}

// Compact photo definitions per property
const P: Record<string, PhotoDef[]> = {
  "Daventry-1309": [
    { f: "main.webp", c: "hero", u: "/properties/Daventry-1309/main.webp" },
    { f: "photo-1.webp", c: "exterior-front", u: "/properties/Daventry-1309/photo-1.webp" },
    { f: "photo-2.webp", c: "exterior-front", u: "/properties/Daventry-1309/photo-2.webp" },
    { f: "photo-3.webp", c: "living-room", u: "/properties/Daventry-1309/photo-3.webp" },
    { f: "photo-4.webp", c: "living-room", u: "/properties/Daventry-1309/photo-4.webp" },
    { f: "photo-5.webp", c: "living-room", u: "/properties/Daventry-1309/photo-5.webp" },
    { f: "photo-6.webp", c: "kitchen", u: "/properties/Daventry-1309/photo-6.webp" },
    { f: "photo-7.webp", c: "kitchen", u: "/properties/Daventry-1309/photo-7.webp" },
    { f: "photo-8.webp", c: "dining-room", u: "/properties/Daventry-1309/photo-8.webp" },
    { f: "photo-9.webp", c: "dining-room", u: "/properties/Daventry-1309/photo-9.webp" },
    { f: "photo-10.webp", c: "bedroom", u: "/properties/Daventry-1309/photo-10.webp" },
    { f: "photo-11.webp", c: "bedroom", u: "/properties/Daventry-1309/photo-11.webp" },
    { f: "photo-12.webp", c: "bedroom", u: "/properties/Daventry-1309/photo-12.webp" },
    { f: "photo-13.webp", c: "master-bedroom", u: "/properties/Daventry-1309/photo-13.webp" },
    { f: "photo-14.webp", c: "master-bedroom", u: "/properties/Daventry-1309/photo-14.webp" },
    { f: "photo-15.webp", c: "bedroom", u: "/properties/Daventry-1309/photo-15.webp" },
    { f: "photo-16.webp", c: "bedroom", u: "/properties/Daventry-1309/photo-16.webp" },
    { f: "photo-17.webp", c: "bathroom", u: "/properties/Daventry-1309/photo-17.webp" },
    { f: "photo-18.webp", c: "bathroom", u: "/properties/Daventry-1309/photo-18.webp" },
    { f: "photo-19.webp", c: "bathroom", u: "/properties/Daventry-1309/photo-19.webp" },
    { f: "photo-20.webp", c: "master-bathroom", u: "/properties/Daventry-1309/photo-20.webp" },
    { f: "photo-21.webp", c: "master-bathroom", u: "/properties/Daventry-1309/photo-21.webp" },
    { f: "photo-22.webp", c: "hallway", u: "/properties/Daventry-1309/photo-22.webp" },
    { f: "photo-23.webp", c: "laundry", u: "/properties/Daventry-1309/photo-23.webp" },
    { f: "photo-24.webp", c: "garage", u: "/properties/Daventry-1309/photo-24.webp" },
    { f: "photo-25.webp", c: "covered-patio", u: "/properties/Daventry-1309/photo-25.webp" },
    { f: "photo-26.webp", c: "covered-patio", u: "/properties/Daventry-1309/photo-26.webp" },
    { f: "photo-27.webp", c: "patio", u: "/properties/Daventry-1309/photo-27.webp" },
    { f: "photo-28.webp", c: "backyard", u: "/properties/Daventry-1309/photo-28.webp" },
    { f: "photo-29.webp", c: "backyard", u: "/properties/Daventry-1309/photo-29.webp" },
    { f: "photo-30.webp", c: "exterior-back", u: "/properties/Daventry-1309/photo-30.webp" },
    { f: "photo-31.webp", c: "exterior-back", u: "/properties/Daventry-1309/photo-31.webp" },
    { f: "photo-32.webp", c: "bedroom", u: "/properties/Daventry-1309/photo-32.webp" },
    { f: "photo-33.webp", c: "bedroom", u: "/properties/Daventry-1309/photo-33.webp" },
    { f: "photo-34.webp", c: "bedroom", u: "/properties/Daventry-1309/photo-34.webp" },
    { f: "photo-35.webp", c: "bedroom", u: "/properties/Daventry-1309/photo-35.webp" },
    { f: "photo-36.webp", c: "games-room", u: "/properties/Daventry-1309/photo-36.webp" },
    { f: "photo-37.webp", c: "games-room", u: "/properties/Daventry-1309/photo-37.webp" },
    { f: "photo-38.webp", c: "games-room", u: "/properties/Daventry-1309/photo-38.webp" },
    { f: "photo-39.webp", c: "living-room", u: "/properties/Daventry-1309/photo-39.webp" },
    { f: "photo-40.webp", c: "living-room", u: "/properties/Daventry-1309/photo-40.webp" },
    { f: "photo-41.webp", c: "kitchen", u: "/properties/Daventry-1309/photo-41.webp" },
    { f: "photo-42.webp", c: "bedroom", u: "/properties/Daventry-1309/photo-42.webp" },
    { f: "photo-43.webp", c: "bedroom", u: "/properties/Daventry-1309/photo-43.webp" },
    { f: "photo-44.webp", c: "bathroom", u: "/properties/Daventry-1309/photo-44.webp" },
    { f: "photo-45.webp", c: "bathroom", u: "/properties/Daventry-1309/photo-45.webp" },
    { f: "photo-46.webp", c: "exterior-front", u: "/properties/Daventry-1309/photo-46.webp" },
    { f: "photo-47.webp", c: "exterior-front", u: "/properties/Daventry-1309/photo-47.webp" },
    { f: "photo-48.webp", c: "yard", u: "/properties/Daventry-1309/photo-48.webp" },
    { f: "photo-49.webp", c: "yard", u: "/properties/Daventry-1309/photo-49.webp" },
  ],
  "Daventry-1311": [
    { f: "main.webp", c: "hero", u: "/properties/Daventry-1311/main.webp" },
    { f: "photo-1.webp", c: "living-room", u: "/properties/Daventry-1311/photo-1.webp" },
    { f: "photo-10.webp", c: "living-room", u: "/properties/Daventry-1311/photo-10.webp" },
    { f: "photo-11.webp", c: "living-room", u: "/properties/Daventry-1311/photo-11.webp" },
    { f: "photo-12.webp", c: "living-room", u: "/properties/Daventry-1311/photo-12.webp" },
    { f: "photo-13.webp", c: "living-room", u: "/properties/Daventry-1311/photo-13.webp" },
    { f: "photo-14.webp", c: "dining-room", u: "/properties/Daventry-1311/photo-14.webp" },
    { f: "photo-15.webp", c: "living-room", u: "/properties/Daventry-1311/photo-15.webp" },
    { f: "photo-16.webp", c: "bedroom", u: "/properties/Daventry-1311/photo-16.webp" },
    { f: "photo-17.webp", c: "dining-room", u: "/properties/Daventry-1311/photo-17.webp" },
    { f: "photo-18.webp", c: "kitchen", u: "/properties/Daventry-1311/photo-18.webp" },
    { f: "photo-19.webp", c: "kitchen", u: "/properties/Daventry-1311/photo-19.webp" },
    { f: "photo-2.webp", c: "exterior-front", u: "/properties/Daventry-1311/photo-2.webp" },
    { f: "photo-20.webp", c: "dining-room", u: "/properties/Daventry-1311/photo-20.webp" },
    { f: "photo-21.webp", c: "dining-room", u: "/properties/Daventry-1311/photo-21.webp" },
    { f: "photo-22.webp", c: "entrance", u: "/properties/Daventry-1311/photo-22.webp" },
    { f: "photo-23.webp", c: "exterior-front", u: "/properties/Daventry-1311/photo-23.webp" },
    { f: "photo-24.webp", c: "games-room", u: "/properties/Daventry-1311/photo-24.webp" },
    { f: "photo-25.webp", c: "games-room", u: "/properties/Daventry-1311/photo-25.webp" },
    { f: "photo-26.webp", c: "games-room", u: "/properties/Daventry-1311/photo-26.webp" },
    { f: "photo-27.webp", c: "games-room", u: "/properties/Daventry-1311/photo-27.webp" },
    { f: "photo-28.webp", c: "bedroom", u: "/properties/Daventry-1311/photo-28.webp" },
    { f: "photo-29.webp", c: "master-bedroom", u: "/properties/Daventry-1311/photo-29.webp" },
    { f: "photo-3.webp", c: "kitchen", u: "/properties/Daventry-1311/photo-3.webp" },
    { f: "photo-30.webp", c: "bedroom", u: "/properties/Daventry-1311/photo-30.webp" },
    { f: "photo-31.webp", c: "master-bedroom", u: "/properties/Daventry-1311/photo-31.webp" },
    { f: "photo-32.webp", c: "bathroom", u: "/properties/Daventry-1311/photo-32.webp" },
    { f: "photo-33.webp", c: "bedroom", u: "/properties/Daventry-1311/photo-33.webp" },
    { f: "photo-34.webp", c: "bedroom", u: "/properties/Daventry-1311/photo-34.webp" },
    { f: "photo-35.webp", c: "bathroom", u: "/properties/Daventry-1311/photo-35.webp" },
    { f: "photo-36.webp", c: "bathroom", u: "/properties/Daventry-1311/photo-36.webp" },
    { f: "photo-37.webp", c: "bathroom", u: "/properties/Daventry-1311/photo-37.webp" },
    { f: "photo-38.webp", c: "bedroom", u: "/properties/Daventry-1311/photo-38.webp" },
    { f: "photo-39.webp", c: "bedroom", u: "/properties/Daventry-1311/photo-39.webp" },
    { f: "photo-4.webp", c: "exterior-front", u: "/properties/Daventry-1311/photo-4.webp" },
    { f: "photo-40.webp", c: "bedroom", u: "/properties/Daventry-1311/photo-40.webp" },
    { f: "photo-41.webp", c: "master-bedroom", u: "/properties/Daventry-1311/photo-41.webp" },
    { f: "photo-42.webp", c: "laundry", u: "/properties/Daventry-1311/photo-42.webp" },
    { f: "photo-43.webp", c: "bedroom", u: "/properties/Daventry-1311/photo-43.webp" },
    { f: "photo-44.webp", c: "master-bedroom", u: "/properties/Daventry-1311/photo-44.webp" },
    { f: "photo-45.webp", c: "master-bedroom", u: "/properties/Daventry-1311/photo-45.webp" },
    { f: "photo-46.webp", c: "bedroom", u: "/properties/Daventry-1311/photo-46.webp" },
    { f: "photo-47.webp", c: "master-bathroom", u: "/properties/Daventry-1311/photo-47.webp" },
    { f: "photo-48.webp", c: "master-bathroom", u: "/properties/Daventry-1311/photo-48.webp" },
    { f: "photo-49.webp", c: "master-bathroom", u: "/properties/Daventry-1311/photo-49.webp" },
    { f: "photo-5.webp", c: "entrance", u: "/properties/Daventry-1311/photo-5.webp" },
    { f: "photo-50.webp", c: "master-bathroom", u: "/properties/Daventry-1311/photo-50.webp" },
    { f: "photo-51.webp", c: "garage", u: "/properties/Daventry-1311/photo-51.webp" },
    { f: "photo-52.webp", c: "games-room", u: "/properties/Daventry-1311/photo-52.webp" },
    { f: "photo-53.webp", c: "games-room", u: "/properties/Daventry-1311/photo-53.webp" },
    { f: "photo-54.webp", c: "games-room", u: "/properties/Daventry-1311/photo-54.webp" },
    { f: "photo-55.webp", c: "games-room", u: "/properties/Daventry-1311/photo-55.webp" },
    { f: "photo-56.webp", c: "covered-patio", u: "/properties/Daventry-1311/photo-56.webp" },
    { f: "photo-57.webp", c: "covered-patio", u: "/properties/Daventry-1311/photo-57.webp" },
    { f: "photo-58.webp", c: "backyard", u: "/properties/Daventry-1311/photo-58.webp" },
    { f: "photo-59.webp", c: "covered-patio", u: "/properties/Daventry-1311/photo-59.webp" },
    { f: "photo-6.webp", c: "exterior-front", u: "/properties/Daventry-1311/photo-6.webp" },
    { f: "photo-60.webp", c: "bathroom", u: "/properties/Daventry-1311/photo-60.webp" },
    { f: "photo-61.webp", c: "backyard", u: "/properties/Daventry-1311/photo-61.webp" },
    { f: "photo-62.webp", c: "backyard", u: "/properties/Daventry-1311/photo-62.webp" },
    { f: "photo-63.webp", c: "patio", u: "/properties/Daventry-1311/photo-63.webp" },
    { f: "photo-7.webp", c: "exterior-front", u: "/properties/Daventry-1311/photo-7.webp" },
    { f: "photo-8.webp", c: "exterior-front", u: "/properties/Daventry-1311/photo-8.webp" },
    { f: "photo-9.webp", c: "exterior-front", u: "/properties/Daventry-1311/photo-9.webp" },
  ],
  "Dentcrest-4707": [
    { f: "main.webp", c: "hero", u: "/properties/Dentcrest-4707/main.webp" },
    { f: "photo-1.webp", c: "covered-patio", u: "/properties/Dentcrest-4707/photo-1.webp" },
    { f: "photo-10.webp", c: "bedroom", u: "/properties/Dentcrest-4707/photo-10.webp" },
    { f: "photo-11.webp", c: "bedroom", u: "/properties/Dentcrest-4707/photo-11.webp" },
    { f: "photo-12.webp", c: "bathroom", u: "/properties/Dentcrest-4707/photo-12.webp" },
    { f: "photo-13.webp", c: "patio", u: "/properties/Dentcrest-4707/photo-13.webp" },
    { f: "photo-14.webp", c: "bedroom", u: "/properties/Dentcrest-4707/photo-14.webp" },
    { f: "photo-15.webp", c: "master-bedroom", u: "/properties/Dentcrest-4707/photo-15.webp" },
    { f: "photo-16.webp", c: "bedroom", u: "/properties/Dentcrest-4707/photo-16.webp" },
    { f: "photo-17.webp", c: "patio", u: "/properties/Dentcrest-4707/photo-17.webp" },
    { f: "photo-18.webp", c: "bedroom", u: "/properties/Dentcrest-4707/photo-18.webp" },
    { f: "photo-19.webp", c: "hallway", u: "/properties/Dentcrest-4707/photo-19.webp" },
    { f: "photo-2.webp", c: "covered-patio", u: "/properties/Dentcrest-4707/photo-2.webp" },
    { f: "photo-20.webp", c: "laundry", u: "/properties/Dentcrest-4707/photo-20.webp" },
    { f: "photo-21.webp", c: "bathroom", u: "/properties/Dentcrest-4707/photo-21.webp" },
    { f: "photo-22.webp", c: "bathroom", u: "/properties/Dentcrest-4707/photo-22.webp" },
    { f: "photo-23.webp", c: "kitchen", u: "/properties/Dentcrest-4707/photo-23.webp" },
    { f: "photo-24.webp", c: "bedroom", u: "/properties/Dentcrest-4707/photo-24.webp" },
    { f: "photo-25.webp", c: "kitchen", u: "/properties/Dentcrest-4707/photo-25.webp" },
    { f: "photo-26.webp", c: "kitchen", u: "/properties/Dentcrest-4707/photo-26.webp" },
    { f: "photo-27.webp", c: "kitchen", u: "/properties/Dentcrest-4707/photo-27.webp" },
    { f: "photo-28.webp", c: "dining-room", u: "/properties/Dentcrest-4707/photo-28.webp" },
    { f: "photo-29.webp", c: "dining-room", u: "/properties/Dentcrest-4707/photo-29.webp" },
    { f: "photo-3.webp", c: "exterior-front", u: "/properties/Dentcrest-4707/photo-3.webp" },
    { f: "photo-30.webp", c: "dining-room", u: "/properties/Dentcrest-4707/photo-30.webp" },
    { f: "photo-31.webp", c: "living-room", u: "/properties/Dentcrest-4707/photo-31.webp" },
    { f: "photo-32.webp", c: "living-room", u: "/properties/Dentcrest-4707/photo-32.webp" },
    { f: "photo-33.webp", c: "living-room", u: "/properties/Dentcrest-4707/photo-33.webp" },
    { f: "photo-34.webp", c: "living-room", u: "/properties/Dentcrest-4707/photo-34.webp" },
    { f: "photo-4.webp", c: "exterior-front", u: "/properties/Dentcrest-4707/photo-4.webp" },
    { f: "photo-5.webp", c: "backyard", u: "/properties/Dentcrest-4707/photo-5.webp" },
    { f: "photo-6.webp", c: "bedroom", u: "/properties/Dentcrest-4707/photo-6.webp" },
    { f: "photo-7.webp", c: "bathroom", u: "/properties/Dentcrest-4707/photo-7.webp" },
    { f: "photo-8.webp", c: "exterior-front", u: "/properties/Dentcrest-4707/photo-8.webp" },
    { f: "photo-9.webp", c: "bathroom", u: "/properties/Dentcrest-4707/photo-9.webp" },
  ],
  "Gleneagles-4735": [
    { f: "main.webp", c: "hero", u: "/properties/Gleneagles-4735/main.webp" },
    { f: "photo-1.webp", c: "living-room", u: "/properties/Gleneagles-4735/photo-1.webp" },
    { f: "photo-10.webp", c: "kitchen", u: "/properties/Gleneagles-4735/photo-10.webp" },
    { f: "photo-11.webp", c: "bedroom", u: "/properties/Gleneagles-4735/photo-11.webp" },
    { f: "photo-12.webp", c: "kitchen", u: "/properties/Gleneagles-4735/photo-12.webp" },
    { f: "photo-13.webp", c: "bedroom", u: "/properties/Gleneagles-4735/photo-13.webp" },
    { f: "photo-14.webp", c: "bedroom", u: "/properties/Gleneagles-4735/photo-14.webp" },
    { f: "photo-15.webp", c: "bathroom", u: "/properties/Gleneagles-4735/photo-15.webp" },
    { f: "photo-16.webp", c: "bathroom", u: "/properties/Gleneagles-4735/photo-16.webp" },
    { f: "photo-17.webp", c: "bedroom", u: "/properties/Gleneagles-4735/photo-17.webp" },
    { f: "photo-18.webp", c: "bathroom", u: "/properties/Gleneagles-4735/photo-18.webp" },
    { f: "photo-19.webp", c: "kitchen", u: "/properties/Gleneagles-4735/photo-19.webp" },
    { f: "photo-2.webp", c: "living-room", u: "/properties/Gleneagles-4735/photo-2.webp" },
    { f: "photo-20.webp", c: "outdoor-dining", u: "/properties/Gleneagles-4735/photo-20.webp" },
    { f: "photo-21.webp", c: "kitchen", u: "/properties/Gleneagles-4735/photo-21.webp" },
    { f: "photo-22.webp", c: "bedroom", u: "/properties/Gleneagles-4735/photo-22.webp" },
    { f: "photo-23.webp", c: "backyard", u: "/properties/Gleneagles-4735/photo-23.webp" },
    { f: "photo-24.webp", c: "kitchen", u: "/properties/Gleneagles-4735/photo-24.webp" },
    { f: "photo-25.webp", c: "patio", u: "/properties/Gleneagles-4735/photo-25.webp" },
    { f: "photo-26.webp", c: "patio", u: "/properties/Gleneagles-4735/photo-26.webp" },
    { f: "photo-27.webp", c: "exterior-front", u: "/properties/Gleneagles-4735/photo-27.webp" },
    { f: "photo-28.webp", c: "bedroom", u: "/properties/Gleneagles-4735/photo-28.webp" },
    { f: "photo-29.webp", c: "exterior-front", u: "/properties/Gleneagles-4735/photo-29.webp" },
    { f: "photo-3.webp", c: "kitchen", u: "/properties/Gleneagles-4735/photo-3.webp" },
    { f: "photo-30.webp", c: "exterior-front", u: "/properties/Gleneagles-4735/photo-30.webp" },
    { f: "photo-31.webp", c: "entrance", u: "/properties/Gleneagles-4735/photo-31.webp" },
    { f: "photo-4.webp", c: "dining-room", u: "/properties/Gleneagles-4735/photo-4.webp" },
    { f: "photo-5.webp", c: "dining-room", u: "/properties/Gleneagles-4735/photo-5.webp" },
    { f: "photo-6.webp", c: "living-room", u: "/properties/Gleneagles-4735/photo-6.webp" },
    { f: "photo-7.webp", c: "kitchen", u: "/properties/Gleneagles-4735/photo-7.webp" },
    { f: "photo-8.webp", c: "kitchen", u: "/properties/Gleneagles-4735/photo-8.webp" },
    { f: "photo-9.webp", c: "kitchen", u: "/properties/Gleneagles-4735/photo-9.webp" },
  ],
  "Golf-Course-3209": [
    { f: "image-01.jpg", c: "unknown", u: "/properties/Golf%20Course-3209/image-01.jpg" },
    { f: "image-02.jpg", c: "unknown", u: "/properties/Golf%20Course-3209/image-02.jpg" },
    { f: "image-03.jpg", c: "unknown", u: "/properties/Golf%20Course-3209/image-03.jpg" },
    { f: "image-04.jpg", c: "unknown", u: "/properties/Golf%20Course-3209/image-04.jpg" },
    { f: "livingroom.webp", c: "living-room", u: "/properties/Golf%20Course-3209/livingroom.webp" },
    { f: "main.webp", c: "hero", u: "/properties/Golf%20Course-3209/main.webp" },
    { f: "photo-1.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-1.webp" },
    { f: "photo-10.webp", c: "dining-room", u: "/properties/Golf%20Course-3209/photo-10.webp" },
    { f: "photo-11.webp", c: "dining-room", u: "/properties/Golf%20Course-3209/photo-11.webp" },
    { f: "photo-12.webp", c: "dining-room", u: "/properties/Golf%20Course-3209/photo-12.webp" },
    { f: "photo-13.webp", c: "dining-room", u: "/properties/Golf%20Course-3209/photo-13.webp" },
    { f: "photo-14.webp", c: "dining-room", u: "/properties/Golf%20Course-3209/photo-14.webp" },
    { f: "photo-15.webp", c: "kitchen", u: "/properties/Golf%20Course-3209/photo-15.webp" },
    { f: "photo-16.webp", c: "exterior-front", u: "/properties/Golf%20Course-3209/photo-16.webp" },
    { f: "photo-17.webp", c: "kitchen", u: "/properties/Golf%20Course-3209/photo-17.webp" },
    { f: "photo-18.webp", c: "kitchen", u: "/properties/Golf%20Course-3209/photo-18.webp" },
    { f: "photo-19.webp", c: "kitchen", u: "/properties/Golf%20Course-3209/photo-19.webp" },
    { f: "photo-2.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-2.webp" },
    { f: "photo-20.webp", c: "kitchen", u: "/properties/Golf%20Course-3209/photo-20.webp" },
    { f: "photo-21.webp", c: "laundry", u: "/properties/Golf%20Course-3209/photo-21.webp" },
    { f: "photo-22.webp", c: "bathroom", u: "/properties/Golf%20Course-3209/photo-22.webp" },
    { f: "photo-23.webp", c: "bathroom", u: "/properties/Golf%20Course-3209/photo-23.webp" },
    { f: "photo-24.webp", c: "bathroom", u: "/properties/Golf%20Course-3209/photo-24.webp" },
    { f: "photo-25.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-25.webp" },
    { f: "photo-26.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-26.webp" },
    { f: "photo-27.webp", c: "exterior-front", u: "/properties/Golf%20Course-3209/photo-27.webp" },
    { f: "photo-28.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-28.webp" },
    { f: "photo-29.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-29.webp" },
    { f: "photo-3.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-3.webp" },
    { f: "photo-30.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-30.webp" },
    { f: "photo-31.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-31.webp" },
    { f: "photo-32.webp", c: "garage", u: "/properties/Golf%20Course-3209/photo-32.webp" },
    { f: "photo-33.webp", c: "garage", u: "/properties/Golf%20Course-3209/photo-33.webp" },
    { f: "photo-34.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-34.webp" },
    { f: "photo-35.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-35.webp" },
    { f: "photo-36.webp", c: "exterior-front", u: "/properties/Golf%20Course-3209/photo-36.webp" },
    { f: "photo-37.webp", c: "exterior-front", u: "/properties/Golf%20Course-3209/photo-37.webp" },
    { f: "photo-38.webp", c: "kitchen", u: "/properties/Golf%20Course-3209/photo-38.webp" },
    { f: "photo-39.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-39.webp" },
    { f: "photo-4.webp", c: "living-room", u: "/properties/Golf%20Course-3209/photo-4.webp" },
    { f: "photo-40.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-40.webp" },
    { f: "photo-41.webp", c: "bathroom", u: "/properties/Golf%20Course-3209/photo-41.webp" },
    { f: "photo-42.webp", c: "bathroom", u: "/properties/Golf%20Course-3209/photo-42.webp" },
    { f: "photo-43.webp", c: "covered-patio", u: "/properties/Golf%20Course-3209/photo-43.webp" },
    { f: "photo-44.webp", c: "covered-patio", u: "/properties/Golf%20Course-3209/photo-44.webp" },
    { f: "photo-45.webp", c: "covered-patio", u: "/properties/Golf%20Course-3209/photo-45.webp" },
    { f: "photo-46.webp", c: "pool", u: "/properties/Golf%20Course-3209/photo-46.webp" },
    { f: "photo-47.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-47.webp" },
    { f: "photo-48.webp", c: "exterior-back", u: "/properties/Golf%20Course-3209/photo-48.webp" },
    { f: "photo-49.webp", c: "pool", u: "/properties/Golf%20Course-3209/photo-49.webp" },
    { f: "photo-5.webp", c: "living-room", u: "/properties/Golf%20Course-3209/photo-5.webp" },
    { f: "photo-50.webp", c: "pool", u: "/properties/Golf%20Course-3209/photo-50.webp" },
    { f: "photo-51.webp", c: "patio", u: "/properties/Golf%20Course-3209/photo-51.webp" },
    { f: "photo-52.webp", c: "backyard", u: "/properties/Golf%20Course-3209/photo-52.webp" },
    { f: "photo-53.webp", c: "exterior-front", u: "/properties/Golf%20Course-3209/photo-53.webp" },
    { f: "photo-54.webp", c: "backyard", u: "/properties/Golf%20Course-3209/photo-54.webp" },
    { f: "photo-55.webp", c: "covered-patio", u: "/properties/Golf%20Course-3209/photo-55.webp" },
    { f: "photo-56.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-56.webp" },
    { f: "photo-57.webp", c: "covered-patio", u: "/properties/Golf%20Course-3209/photo-57.webp" },
    { f: "photo-58.webp", c: "covered-patio", u: "/properties/Golf%20Course-3209/photo-58.webp" },
    { f: "photo-59.webp", c: "yard", u: "/properties/Golf%20Course-3209/photo-59.webp" },
    { f: "photo-6.webp", c: "living-room", u: "/properties/Golf%20Course-3209/photo-6.webp" },
    { f: "photo-60.webp", c: "covered-patio", u: "/properties/Golf%20Course-3209/photo-60.webp" },
    { f: "photo-61.webp", c: "covered-patio", u: "/properties/Golf%20Course-3209/photo-61.webp" },
    { f: "photo-62.webp", c: "pool", u: "/properties/Golf%20Course-3209/photo-62.webp" },
    { f: "photo-63.webp", c: "patio", u: "/properties/Golf%20Course-3209/photo-63.webp" },
    { f: "photo-64.webp", c: "patio", u: "/properties/Golf%20Course-3209/photo-64.webp" },
    { f: "photo-65.webp", c: "outdoor-dining", u: "/properties/Golf%20Course-3209/photo-65.webp" },
    { f: "photo-66.webp", c: "patio", u: "/properties/Golf%20Course-3209/photo-66.webp" },
    { f: "photo-67.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-67.webp" },
    { f: "photo-68.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-68.webp" },
    { f: "photo-69.webp", c: "bathroom", u: "/properties/Golf%20Course-3209/photo-69.webp" },
    { f: "photo-7.webp", c: "living-room", u: "/properties/Golf%20Course-3209/photo-7.webp" },
    { f: "photo-70.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-70.webp" },
    { f: "photo-71.webp", c: "bathroom", u: "/properties/Golf%20Course-3209/photo-71.webp" },
    { f: "photo-72.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-72.webp" },
    { f: "photo-73.webp", c: "bedroom", u: "/properties/Golf%20Course-3209/photo-73.webp" },
    { f: "photo-74.webp", c: "exterior-front", u: "/properties/Golf%20Course-3209/photo-74.webp" },
    { f: "photo-8.webp", c: "hallway", u: "/properties/Golf%20Course-3209/photo-8.webp" },
    { f: "photo-9.webp", c: "bathroom", u: "/properties/Golf%20Course-3209/photo-9.webp" },
    { f: "pool.webp", c: "pool", u: "/properties/Golf%20Course-3209/pool.webp" },
    { f: "room 2b.webp", c: "room 2b", u: "/properties/Golf%20Course-3209/room%202b.webp" },
  ],
  "Humble-3106": [
    { f: "main.webp", c: "hero", u: "/properties/Humble-3106/main.webp" },
    { f: "photo-1.webp", c: "covered-patio", u: "/properties/Humble-3106/photo-1.webp" },
    { f: "photo-10.webp", c: "kitchen", u: "/properties/Humble-3106/photo-10.webp" },
    { f: "photo-11.webp", c: "kitchen", u: "/properties/Humble-3106/photo-11.webp" },
    { f: "photo-12.webp", c: "dining-room", u: "/properties/Humble-3106/photo-12.webp" },
    { f: "photo-13.webp", c: "kitchen", u: "/properties/Humble-3106/photo-13.webp" },
    { f: "photo-14.webp", c: "bathroom", u: "/properties/Humble-3106/photo-14.webp" },
    { f: "photo-15.webp", c: "laundry", u: "/properties/Humble-3106/photo-15.webp" },
    { f: "photo-16.webp", c: "bedroom", u: "/properties/Humble-3106/photo-16.webp" },
    { f: "photo-17.webp", c: "bedroom", u: "/properties/Humble-3106/photo-17.webp" },
    { f: "photo-18.webp", c: "bedroom", u: "/properties/Humble-3106/photo-18.webp" },
    { f: "photo-19.webp", c: "bedroom", u: "/properties/Humble-3106/photo-19.webp" },
    { f: "photo-2.webp", c: "exterior-front", u: "/properties/Humble-3106/photo-2.webp" },
    { f: "photo-20.webp", c: "bedroom", u: "/properties/Humble-3106/photo-20.webp" },
    { f: "photo-21.webp", c: "bedroom", u: "/properties/Humble-3106/photo-21.webp" },
    { f: "photo-22.webp", c: "bedroom", u: "/properties/Humble-3106/photo-22.webp" },
    { f: "photo-23.webp", c: "bedroom", u: "/properties/Humble-3106/photo-23.webp" },
    { f: "photo-24.webp", c: "bedroom", u: "/properties/Humble-3106/photo-24.webp" },
    { f: "photo-25.webp", c: "bedroom", u: "/properties/Humble-3106/photo-25.webp" },
    { f: "photo-26.webp", c: "bedroom", u: "/properties/Humble-3106/photo-26.webp" },
    { f: "photo-27.webp", c: "bathroom", u: "/properties/Humble-3106/photo-27.webp" },
    { f: "photo-28.webp", c: "bathroom", u: "/properties/Humble-3106/photo-28.webp" },
    { f: "photo-29.webp", c: "bathroom", u: "/properties/Humble-3106/photo-29.webp" },
    { f: "photo-3.webp", c: "dining-room", u: "/properties/Humble-3106/photo-3.webp" },
    { f: "photo-30.webp", c: "bathroom", u: "/properties/Humble-3106/photo-30.webp" },
    { f: "photo-31.webp", c: "bathroom", u: "/properties/Humble-3106/photo-31.webp" },
    { f: "photo-32.webp", c: "bedroom", u: "/properties/Humble-3106/photo-32.webp" },
    { f: "photo-33.webp", c: "bedroom", u: "/properties/Humble-3106/photo-33.webp" },
    { f: "photo-34.webp", c: "covered-patio", u: "/properties/Humble-3106/photo-34.webp" },
    { f: "photo-35.webp", c: "covered-patio", u: "/properties/Humble-3106/photo-35.webp" },
    { f: "photo-36.webp", c: "pool", u: "/properties/Humble-3106/photo-36.webp" },
    { f: "photo-37.webp", c: "pool", u: "/properties/Humble-3106/photo-37.webp" },
    { f: "photo-38.webp", c: "covered-patio", u: "/properties/Humble-3106/photo-38.webp" },
    { f: "photo-39.webp", c: "patio", u: "/properties/Humble-3106/photo-39.webp" },
    { f: "photo-4.webp", c: "living-room", u: "/properties/Humble-3106/photo-4.webp" },
    { f: "photo-40.webp", c: "covered-patio", u: "/properties/Humble-3106/photo-40.webp" },
    { f: "photo-41.webp", c: "covered-patio", u: "/properties/Humble-3106/photo-41.webp" },
    { f: "photo-42.webp", c: "covered-patio", u: "/properties/Humble-3106/photo-42.webp" },
    { f: "photo-43.webp", c: "pool", u: "/properties/Humble-3106/photo-43.webp" },
    { f: "photo-44.webp", c: "pool", u: "/properties/Humble-3106/photo-44.webp" },
    { f: "photo-45.webp", c: "exterior-front", u: "/properties/Humble-3106/photo-45.webp" },
    { f: "photo-46.webp", c: "exterior-front", u: "/properties/Humble-3106/photo-46.webp" },
    { f: "photo-47.webp", c: "living-room", u: "/properties/Humble-3106/photo-47.webp" },
    { f: "photo-48.webp", c: "pool", u: "/properties/Humble-3106/photo-48.webp" },
    { f: "photo-5.webp", c: "living-room", u: "/properties/Humble-3106/photo-5.webp" },
    { f: "photo-6.webp", c: "hallway", u: "/properties/Humble-3106/photo-6.webp" },
    { f: "photo-7.webp", c: "dining-room", u: "/properties/Humble-3106/photo-7.webp" },
    { f: "photo-8.webp", c: "kitchen", u: "/properties/Humble-3106/photo-8.webp" },
    { f: "photo-9.webp", c: "living-room", u: "/properties/Humble-3106/photo-9.webp" },
  ],
  "posh-private-1426": [
    { f: "main.webp", c: "hero", u: "/properties/Lanham-1426/main.webp" },
    { f: "photo-1.webp", c: "dining-room", u: "/properties/Lanham-1426/photo-1.webp" },
    { f: "photo-10.webp", c: "dining-room", u: "/properties/Lanham-1426/photo-10.webp" },
    { f: "photo-11.webp", c: "dining-room", u: "/properties/Lanham-1426/photo-11.webp" },
    { f: "photo-12.webp", c: "kitchen", u: "/properties/Lanham-1426/photo-12.webp" },
    { f: "photo-13.webp", c: "kitchen", u: "/properties/Lanham-1426/photo-13.webp" },
    { f: "photo-14.webp", c: "living-room", u: "/properties/Lanham-1426/photo-14.webp" },
    { f: "photo-15.webp", c: "dining-room", u: "/properties/Lanham-1426/photo-15.webp" },
    { f: "photo-16.webp", c: "living-room", u: "/properties/Lanham-1426/photo-16.webp" },
    { f: "photo-17.webp", c: "exterior-front", u: "/properties/Lanham-1426/photo-17.webp" },
    { f: "photo-18.webp", c: "bathroom", u: "/properties/Lanham-1426/photo-18.webp" },
    { f: "photo-19.webp", c: "kitchen", u: "/properties/Lanham-1426/photo-19.webp" },
    { f: "photo-2.webp", c: "living-room", u: "/properties/Lanham-1426/photo-2.webp" },
    { f: "photo-20.webp", c: "kitchen", u: "/properties/Lanham-1426/photo-20.webp" },
    { f: "photo-21.webp", c: "living-room", u: "/properties/Lanham-1426/photo-21.webp" },
    { f: "photo-22.webp", c: "living-room", u: "/properties/Lanham-1426/photo-22.webp" },
    { f: "photo-23.webp", c: "exterior-front", u: "/properties/Lanham-1426/photo-23.webp" },
    { f: "photo-24.webp", c: "exterior-front", u: "/properties/Lanham-1426/photo-24.webp" },
    { f: "photo-25.webp", c: "entrance", u: "/properties/Lanham-1426/photo-25.webp" },
    { f: "photo-26.webp", c: "bathroom", u: "/properties/Lanham-1426/photo-26.webp" },
    { f: "photo-27.webp", c: "bathroom", u: "/properties/Lanham-1426/photo-27.webp" },
    { f: "photo-28.webp", c: "patio", u: "/properties/Lanham-1426/photo-28.webp" },
    { f: "photo-29.webp", c: "backyard", u: "/properties/Lanham-1426/photo-29.webp" },
    { f: "photo-3.webp", c: "bedroom", u: "/properties/Lanham-1426/photo-3.webp" },
    { f: "photo-30.webp", c: "exterior-front", u: "/properties/Lanham-1426/photo-30.webp" },
    { f: "photo-31.webp", c: "games-room", u: "/properties/Lanham-1426/photo-31.webp" },
    { f: "photo-32.webp", c: "games-room", u: "/properties/Lanham-1426/photo-32.webp" },
    { f: "photo-33.webp", c: "bathroom", u: "/properties/Lanham-1426/photo-33.webp" },
    { f: "photo-34.webp", c: "master-bedroom", u: "/properties/Lanham-1426/photo-34.webp" },
    { f: "photo-35.webp", c: "bedroom", u: "/properties/Lanham-1426/photo-35.webp" },
    { f: "photo-36.webp", c: "bedroom", u: "/properties/Lanham-1426/photo-36.webp" },
    { f: "photo-37.webp", c: "bathroom", u: "/properties/Lanham-1426/photo-37.webp" },
    { f: "photo-38.webp", c: "bathroom", u: "/properties/Lanham-1426/photo-38.webp" },
    { f: "photo-39.webp", c: "backyard", u: "/properties/Lanham-1426/photo-39.webp" },
    { f: "photo-4.webp", c: "laundry", u: "/properties/Lanham-1426/photo-4.webp" },
    { f: "photo-40.webp", c: "backyard", u: "/properties/Lanham-1426/photo-40.webp" },
    { f: "photo-41.webp", c: "backyard", u: "/properties/Lanham-1426/photo-41.webp" },
    { f: "photo-5.webp", c: "kitchen", u: "/properties/Lanham-1426/photo-5.webp" },
    { f: "photo-6.webp", c: "bathroom", u: "/properties/Lanham-1426/photo-6.webp" },
    { f: "photo-7.webp", c: "bathroom", u: "/properties/Lanham-1426/photo-7.webp" },
    { f: "photo-8.webp", c: "bathroom", u: "/properties/Lanham-1426/photo-8.webp" },
    { f: "photo-9.webp", c: "dining-room", u: "/properties/Lanham-1426/photo-9.webp" },
  ],
  "Mogford-1408": [
    { f: "main.webp", c: "hero", u: "/properties/Mogford-1408/main.webp" },
    { f: "photo-1.webp", c: "pool", u: "/properties/Mogford-1408/photo-1.webp" },
    { f: "photo-10.webp", c: "kitchen", u: "/properties/Mogford-1408/photo-10.webp" },
    { f: "photo-11.webp", c: "living-room", u: "/properties/Mogford-1408/photo-11.webp" },
    { f: "photo-12.webp", c: "bedroom", u: "/properties/Mogford-1408/photo-12.webp" },
    { f: "photo-13.webp", c: "kitchen", u: "/properties/Mogford-1408/photo-13.webp" },
    { f: "photo-14.webp", c: "bedroom", u: "/properties/Mogford-1408/photo-14.webp" },
    { f: "photo-15.webp", c: "dining-room", u: "/properties/Mogford-1408/photo-15.webp" },
    { f: "photo-16.webp", c: "bedroom", u: "/properties/Mogford-1408/photo-16.webp" },
    { f: "photo-17.webp", c: "exterior-front", u: "/properties/Mogford-1408/photo-17.webp" },
    { f: "photo-18.webp", c: "bedroom", u: "/properties/Mogford-1408/photo-18.webp" },
    { f: "photo-19.webp", c: "bedroom", u: "/properties/Mogford-1408/photo-19.webp" },
    { f: "photo-2.webp", c: "games-room", u: "/properties/Mogford-1408/photo-2.webp" },
    { f: "photo-20.webp", c: "bedroom", u: "/properties/Mogford-1408/photo-20.webp" },
    { f: "photo-21.webp", c: "covered-patio", u: "/properties/Mogford-1408/photo-21.webp" },
    { f: "photo-22.webp", c: "pool", u: "/properties/Mogford-1408/photo-22.webp" },
    { f: "photo-23.webp", c: "exterior-front", u: "/properties/Mogford-1408/photo-23.webp" },
    { f: "photo-24.webp", c: "yard", u: "/properties/Mogford-1408/photo-24.webp" },
    { f: "photo-25.webp", c: "backyard", u: "/properties/Mogford-1408/photo-25.webp" },
    { f: "photo-26.webp", c: "bathroom", u: "/properties/Mogford-1408/photo-26.webp" },
    { f: "photo-27.webp", c: "bathroom", u: "/properties/Mogford-1408/photo-27.webp" },
    { f: "photo-28.webp", c: "bedroom", u: "/properties/Mogford-1408/photo-28.webp" },
    { f: "photo-29.webp", c: "bedroom", u: "/properties/Mogford-1408/photo-29.webp" },
    { f: "photo-3.webp", c: "living-room", u: "/properties/Mogford-1408/photo-3.webp" },
    { f: "photo-30.webp", c: "bedroom", u: "/properties/Mogford-1408/photo-30.webp" },
    { f: "photo-31.webp", c: "bathroom", u: "/properties/Mogford-1408/photo-31.webp" },
    { f: "photo-32.webp", c: "bedroom", u: "/properties/Mogford-1408/photo-32.webp" },
    { f: "photo-33.webp", c: "covered-patio", u: "/properties/Mogford-1408/photo-33.webp" },
    { f: "photo-34.webp", c: "bathroom", u: "/properties/Mogford-1408/photo-34.webp" },
    { f: "photo-4.webp", c: "exterior-front", u: "/properties/Mogford-1408/photo-4.webp" },
    { f: "photo-5.webp", c: "kitchen", u: "/properties/Mogford-1408/photo-5.webp" },
    { f: "photo-6.webp", c: "bedroom", u: "/properties/Mogford-1408/photo-6.webp" },
    { f: "photo-7.webp", c: "dining-room", u: "/properties/Mogford-1408/photo-7.webp" },
    { f: "photo-8.webp", c: "kitchen", u: "/properties/Mogford-1408/photo-8.webp" },
    { f: "photo-9.webp", c: "bathroom", u: "/properties/Mogford-1408/photo-9.webp" },
  ],
  "Oriole-6100": [
    { f: "main.webp", c: "hero", u: "/properties/Oriole-6100/main.webp" },
    { f: "photo-1.webp", c: "dining-room", u: "/properties/Oriole-6100/photo-1.webp" },
    { f: "photo-10.webp", c: "laundry", u: "/properties/Oriole-6100/photo-10.webp" },
    { f: "photo-11.webp", c: "bathroom", u: "/properties/Oriole-6100/photo-11.webp" },
    { f: "photo-12.webp", c: "bedroom", u: "/properties/Oriole-6100/photo-12.webp" },
    { f: "photo-13.webp", c: "bathroom", u: "/properties/Oriole-6100/photo-13.webp" },
    { f: "photo-14.webp", c: "bedroom", u: "/properties/Oriole-6100/photo-14.webp" },
    { f: "photo-15.webp", c: "master-bedroom", u: "/properties/Oriole-6100/photo-15.webp" },
    { f: "photo-16.webp", c: "bedroom", u: "/properties/Oriole-6100/photo-16.webp" },
    { f: "photo-17.webp", c: "dining-room", u: "/properties/Oriole-6100/photo-17.webp" },
    { f: "photo-18.webp", c: "dining-room", u: "/properties/Oriole-6100/photo-18.webp" },
    { f: "photo-19.webp", c: "pool", u: "/properties/Oriole-6100/photo-19.webp" },
    { f: "photo-2.webp", c: "pool", u: "/properties/Oriole-6100/photo-2.webp" },
    { f: "photo-20.webp", c: "bedroom", u: "/properties/Oriole-6100/photo-20.webp" },
    { f: "photo-21.webp", c: "dining-room", u: "/properties/Oriole-6100/photo-21.webp" },
    { f: "photo-22.webp", c: "bathroom", u: "/properties/Oriole-6100/photo-22.webp" },
    { f: "photo-23.webp", c: "living-room", u: "/properties/Oriole-6100/photo-23.webp" },
    { f: "photo-24.webp", c: "kitchen", u: "/properties/Oriole-6100/photo-24.webp" },
    { f: "photo-25.webp", c: "bedroom", u: "/properties/Oriole-6100/photo-25.webp" },
    { f: "photo-26.webp", c: "bedroom", u: "/properties/Oriole-6100/photo-26.webp" },
    { f: "photo-27.webp", c: "bedroom", u: "/properties/Oriole-6100/photo-27.webp" },
    { f: "photo-28.webp", c: "bedroom", u: "/properties/Oriole-6100/photo-28.webp" },
    { f: "photo-29.webp", c: "pool", u: "/properties/Oriole-6100/photo-29.webp" },
    { f: "photo-3.webp", c: "living-room", u: "/properties/Oriole-6100/photo-3.webp" },
    { f: "photo-30.webp", c: "dining-room", u: "/properties/Oriole-6100/photo-30.webp" },
    { f: "photo-31.webp", c: "bathroom", u: "/properties/Oriole-6100/photo-31.webp" },
    { f: "photo-32.webp", c: "bathroom", u: "/properties/Oriole-6100/photo-32.webp" },
    { f: "photo-33.webp", c: "bedroom", u: "/properties/Oriole-6100/photo-33.webp" },
    { f: "photo-4.webp", c: "living-room", u: "/properties/Oriole-6100/photo-4.webp" },
    { f: "photo-5.webp", c: "covered-patio", u: "/properties/Oriole-6100/photo-5.webp" },
    { f: "photo-6.webp", c: "covered-patio", u: "/properties/Oriole-6100/photo-6.webp" },
    { f: "photo-7.webp", c: "dining-room", u: "/properties/Oriole-6100/photo-7.webp" },
    { f: "photo-8.webp", c: "kitchen", u: "/properties/Oriole-6100/photo-8.webp" },
    { f: "photo-9.webp", c: "kitchen", u: "/properties/Oriole-6100/photo-9.webp" },
  ],
  "Siesta-4217": [
    { f: "main.webp", c: "hero", u: "/properties/Siesta-4217/main.webp" },
    { f: "photo-1.webp", c: "living-room", u: "/properties/Siesta-4217/photo-1.webp" },
    { f: "photo-10.webp", c: "living-room", u: "/properties/Siesta-4217/photo-10.webp" },
    { f: "photo-11.webp", c: "bedroom", u: "/properties/Siesta-4217/photo-11.webp" },
    { f: "photo-12.webp", c: "exterior-front", u: "/properties/Siesta-4217/photo-12.webp" },
    { f: "photo-13.webp", c: "exterior-front", u: "/properties/Siesta-4217/photo-13.webp" },
    { f: "photo-14.webp", c: "bathroom", u: "/properties/Siesta-4217/photo-14.webp" },
    { f: "photo-15.webp", c: "laundry", u: "/properties/Siesta-4217/photo-15.webp" },
    { f: "photo-2.webp", c: "living-room", u: "/properties/Siesta-4217/photo-2.webp" },
    { f: "photo-3.webp", c: "dining-room", u: "/properties/Siesta-4217/photo-3.webp" },
    { f: "photo-4.webp", c: "kitchen", u: "/properties/Siesta-4217/photo-4.webp" },
    { f: "photo-5.webp", c: "kitchen", u: "/properties/Siesta-4217/photo-5.webp" },
    { f: "photo-6.webp", c: "bedroom", u: "/properties/Siesta-4217/photo-6.webp" },
    { f: "photo-7.webp", c: "bedroom", u: "/properties/Siesta-4217/photo-7.webp" },
    { f: "photo-8.webp", c: "bedroom", u: "/properties/Siesta-4217/photo-8.webp" },
    { f: "photo-9.webp", c: "bathroom", u: "/properties/Siesta-4217/photo-9.webp" },
  ],
  "Vanguard-1633": [
    { f: "main.webp", c: "hero", u: "/properties/Vanguard-1633/main.webp" },
    { f: "photo-1.webp", c: "living-room", u: "/properties/Vanguard-1633/photo-1.webp" },
    { f: "photo-10.webp", c: "bedroom", u: "/properties/Vanguard-1633/photo-10.webp" },
    { f: "photo-11.webp", c: "bathroom", u: "/properties/Vanguard-1633/photo-11.webp" },
    { f: "photo-12.webp", c: "bedroom", u: "/properties/Vanguard-1633/photo-12.webp" },
    { f: "photo-13.webp", c: "exterior-front", u: "/properties/Vanguard-1633/photo-13.webp" },
    { f: "photo-14.webp", c: "covered-patio", u: "/properties/Vanguard-1633/photo-14.webp" },
    { f: "photo-15.webp", c: "exterior-front", u: "/properties/Vanguard-1633/photo-15.webp" },
    { f: "photo-16.webp", c: "bedroom", u: "/properties/Vanguard-1633/photo-16.webp" },
    { f: "photo-17.webp", c: "bathroom", u: "/properties/Vanguard-1633/photo-17.webp" },
    { f: "photo-18.webp", c: "living-room", u: "/properties/Vanguard-1633/photo-18.webp" },
    { f: "photo-19.webp", c: "kitchen", u: "/properties/Vanguard-1633/photo-19.webp" },
    { f: "photo-2.webp", c: "kitchen", u: "/properties/Vanguard-1633/photo-2.webp" },
    { f: "photo-20.webp", c: "master-bedroom", u: "/properties/Vanguard-1633/photo-20.webp" },
    { f: "photo-21.webp", c: "bedroom", u: "/properties/Vanguard-1633/photo-21.webp" },
    { f: "photo-22.webp", c: "living-room", u: "/properties/Vanguard-1633/photo-22.webp" },
    { f: "photo-23.webp", c: "living-room", u: "/properties/Vanguard-1633/photo-23.webp" },
    { f: "photo-24.webp", c: "bathroom", u: "/properties/Vanguard-1633/photo-24.webp" },
    { f: "photo-25.webp", c: "backyard", u: "/properties/Vanguard-1633/photo-25.webp" },
    { f: "photo-26.webp", c: "covered-patio", u: "/properties/Vanguard-1633/photo-26.webp" },
    { f: "photo-27.webp", c: "entrance", u: "/properties/Vanguard-1633/photo-27.webp" },
    { f: "photo-28.webp", c: "hallway", u: "/properties/Vanguard-1633/photo-28.webp" },
    { f: "photo-29.webp", c: "entrance", u: "/properties/Vanguard-1633/photo-29.webp" },
    { f: "photo-3.webp", c: "kitchen", u: "/properties/Vanguard-1633/photo-3.webp" },
    { f: "photo-30.webp", c: "laundry", u: "/properties/Vanguard-1633/photo-30.webp" },
    { f: "photo-4.webp", c: "kitchen", u: "/properties/Vanguard-1633/photo-4.webp" },
    { f: "photo-5.webp", c: "kitchen", u: "/properties/Vanguard-1633/photo-5.webp" },
    { f: "photo-6.webp", c: "bedroom", u: "/properties/Vanguard-1633/photo-6.webp" },
    { f: "photo-7.webp", c: "bedroom", u: "/properties/Vanguard-1633/photo-7.webp" },
    { f: "photo-8.webp", c: "bedroom", u: "/properties/Vanguard-1633/photo-8.webp" },
    { f: "photo-9.webp", c: "bedroom", u: "/properties/Vanguard-1633/photo-9.webp" },
  ],
  "Vanguard-6613": [
    { f: "main.webp", c: "hero", u: "/properties/Vanguard-6613/main.webp" },
    { f: "photo-1.webp", c: "living-room", u: "/properties/Vanguard-6613/photo-1.webp" },
    { f: "photo-10.webp", c: "bedroom", u: "/properties/Vanguard-6613/photo-10.webp" },
    { f: "photo-11.webp", c: "bathroom", u: "/properties/Vanguard-6613/photo-11.webp" },
    { f: "photo-12.webp", c: "bedroom", u: "/properties/Vanguard-6613/photo-12.webp" },
    { f: "photo-13.webp", c: "exterior-front", u: "/properties/Vanguard-6613/photo-13.webp" },
    { f: "photo-14.webp", c: "covered-patio", u: "/properties/Vanguard-6613/photo-14.webp" },
    { f: "photo-15.webp", c: "exterior-front", u: "/properties/Vanguard-6613/photo-15.webp" },
    { f: "photo-16.webp", c: "bedroom", u: "/properties/Vanguard-6613/photo-16.webp" },
    { f: "photo-17.webp", c: "bathroom", u: "/properties/Vanguard-6613/photo-17.webp" },
    { f: "photo-18.webp", c: "living-room", u: "/properties/Vanguard-6613/photo-18.webp" },
    { f: "photo-19.webp", c: "kitchen", u: "/properties/Vanguard-6613/photo-19.webp" },
    { f: "photo-2.webp", c: "kitchen", u: "/properties/Vanguard-6613/photo-2.webp" },
    { f: "photo-20.webp", c: "master-bedroom", u: "/properties/Vanguard-6613/photo-20.webp" },
    { f: "photo-21.webp", c: "bedroom", u: "/properties/Vanguard-6613/photo-21.webp" },
    { f: "photo-22.webp", c: "living-room", u: "/properties/Vanguard-6613/photo-22.webp" },
    { f: "photo-23.webp", c: "living-room", u: "/properties/Vanguard-6613/photo-23.webp" },
    { f: "photo-24.webp", c: "bathroom", u: "/properties/Vanguard-6613/photo-24.webp" },
    { f: "photo-25.webp", c: "backyard", u: "/properties/Vanguard-6613/photo-25.webp" },
    { f: "photo-26.webp", c: "covered-patio", u: "/properties/Vanguard-6613/photo-26.webp" },
    { f: "photo-27.webp", c: "entrance", u: "/properties/Vanguard-6613/photo-27.webp" },
    { f: "photo-28.webp", c: "hallway", u: "/properties/Vanguard-6613/photo-28.webp" },
    { f: "photo-29.webp", c: "entrance", u: "/properties/Vanguard-6613/photo-29.webp" },
    { f: "photo-3.webp", c: "kitchen", u: "/properties/Vanguard-6613/photo-3.webp" },
    { f: "photo-30.webp", c: "laundry", u: "/properties/Vanguard-6613/photo-30.webp" },
    { f: "photo-4.webp", c: "kitchen", u: "/properties/Vanguard-6613/photo-4.webp" },
    { f: "photo-5.webp", c: "kitchen", u: "/properties/Vanguard-6613/photo-5.webp" },
    { f: "photo-6.webp", c: "bedroom", u: "/properties/Vanguard-6613/photo-6.webp" },
    { f: "photo-7.webp", c: "bedroom", u: "/properties/Vanguard-6613/photo-7.webp" },
    { f: "photo-8.webp", c: "bedroom", u: "/properties/Vanguard-6613/photo-8.webp" },
    { f: "photo-9.webp", c: "bedroom", u: "/properties/Vanguard-6613/photo-9.webp" },
  ],
  "castleford-5001": [
    { f: "bathroom-10.webp", c: "bathroom", u: "/properties/castleford-5001/bathroom-10.webp" },
    { f: "bathroom-11.webp", c: "bathroom", u: "/properties/castleford-5001/bathroom-11.webp" },
    { f: "bathroom-12.webp", c: "bathroom", u: "/properties/castleford-5001/bathroom-12.webp" },
    { f: "bathroom-2.webp", c: "bathroom", u: "/properties/castleford-5001/bathroom-2.webp" },
    { f: "bathroom-3.webp", c: "bathroom", u: "/properties/castleford-5001/bathroom-3.webp" },
    { f: "bathroom-4.webp", c: "bathroom", u: "/properties/castleford-5001/bathroom-4.webp" },
    { f: "bathroom-5.webp", c: "bathroom", u: "/properties/castleford-5001/bathroom-5.webp" },
    { f: "bathroom-6.webp", c: "bathroom", u: "/properties/castleford-5001/bathroom-6.webp" },
    { f: "bathroom-7.webp", c: "bathroom", u: "/properties/castleford-5001/bathroom-7.webp" },
    { f: "bathroom-8.webp", c: "bathroom", u: "/properties/castleford-5001/bathroom-8.webp" },
    { f: "bathroom-9.webp", c: "bathroom", u: "/properties/castleford-5001/bathroom-9.webp" },
    { f: "bathroom.webp", c: "bathroom", u: "/properties/castleford-5001/bathroom.webp" },
    { f: "dining-2.webp", c: "dining-room", u: "/properties/castleford-5001/dining-2.webp" },
    { f: "dining-3.webp", c: "dining-room", u: "/properties/castleford-5001/dining-3.webp" },
    { f: "dining.webp", c: "dining-room", u: "/properties/castleford-5001/dining.webp" },
    { f: "exterior-2.webp", c: "exterior-front", u: "/properties/castleford-5001/exterior-2.webp" },
    { f: "exterior-3.webp", c: "exterior-front", u: "/properties/castleford-5001/exterior-3.webp" },
    { f: "exterior-4.webp", c: "exterior-front", u: "/properties/castleford-5001/exterior-4.webp" },
    { f: "exterior-5.webp", c: "exterior-front", u: "/properties/castleford-5001/exterior-5.webp" },
    { f: "exterior-6.webp", c: "exterior-front", u: "/properties/castleford-5001/exterior-6.webp" },
    { f: "exterior-7.webp", c: "exterior-front", u: "/properties/castleford-5001/exterior-7.webp" },
    { f: "exterior-8.webp", c: "exterior-front", u: "/properties/castleford-5001/exterior-8.webp" },
    { f: "exterior-detail.webp", c: "exterior-front", u: "/properties/castleford-5001/exterior-detail.webp" },
    { f: "exterior.webp", c: "exterior-front", u: "/properties/castleford-5001/exterior.webp" },
    { f: "games-room-2.webp", c: "games-room", u: "/properties/castleford-5001/games-room-2.webp" },
    { f: "games-room-3.webp", c: "games-room", u: "/properties/castleford-5001/games-room-3.webp" },
    { f: "games-room-4.webp", c: "games-room", u: "/properties/castleford-5001/games-room-4.webp" },
    { f: "games-room-5.webp", c: "games-room", u: "/properties/castleford-5001/games-room-5.webp" },
    { f: "games-room.webp", c: "games-room", u: "/properties/castleford-5001/games-room.webp" },
    { f: "interior-2.webp", c: "living-room", u: "/properties/castleford-5001/interior-2.webp" },
    { f: "interior.webp", c: "living-room", u: "/properties/castleford-5001/interior.webp" },
    { f: "living-area-2.webp", c: "living-room", u: "/properties/castleford-5001/living-area-2.webp" },
    { f: "living-area-3.webp", c: "living-room", u: "/properties/castleford-5001/living-area-3.webp" },
    { f: "living-area-4.webp", c: "living-room", u: "/properties/castleford-5001/living-area-4.webp" },
    { f: "living-area-5.webp", c: "living-room", u: "/properties/castleford-5001/living-area-5.webp" },
    { f: "living-area.webp", c: "living-room", u: "/properties/castleford-5001/living-area.webp" },
    { f: "main.webp", c: "hero", u: "/properties/castleford-5001/main.webp" },
    { f: "outdoor-dining-2.webp", c: "outdoor-dining", u: "/properties/castleford-5001/outdoor-dining-2.webp" },
    { f: "outdoor-dining-3.webp", c: "outdoor-dining", u: "/properties/castleford-5001/outdoor-dining-3.webp" },
    { f: "outdoor-dining.webp", c: "outdoor-dining", u: "/properties/castleford-5001/outdoor-dining.webp" },
    { f: "photo-1.webp", c: "kitchen", u: "/properties/castleford-5001/photo-1.webp" },
    { f: "photo-10.webp", c: "bedroom", u: "/properties/castleford-5001/photo-10.webp" },
    { f: "photo-11.webp", c: "bedroom", u: "/properties/castleford-5001/photo-11.webp" },
    { f: "photo-12.webp", c: "master-bedroom", u: "/properties/castleford-5001/photo-12.webp" },
    { f: "photo-13.webp", c: "exterior-front", u: "/properties/castleford-5001/photo-13.webp" },
    { f: "photo-14.webp", c: "bedroom", u: "/properties/castleford-5001/photo-14.webp" },
    { f: "photo-15.webp", c: "bathroom", u: "/properties/castleford-5001/photo-15.webp" },
    { f: "photo-16.webp", c: "master-bathroom", u: "/properties/castleford-5001/photo-16.webp" },
    { f: "photo-17.webp", c: "bedroom", u: "/properties/castleford-5001/photo-17.webp" },
    { f: "photo-18.webp", c: "bathroom", u: "/properties/castleford-5001/photo-18.webp" },
    { f: "photo-19.webp", c: "bathroom", u: "/properties/castleford-5001/photo-19.webp" },
    { f: "photo-2.webp", c: "dining-room", u: "/properties/castleford-5001/photo-2.webp" },
    { f: "photo-20.webp", c: "master-bathroom", u: "/properties/castleford-5001/photo-20.webp" },
    { f: "photo-21.webp", c: "bathroom", u: "/properties/castleford-5001/photo-21.webp" },
    { f: "photo-22.webp", c: "bedroom", u: "/properties/castleford-5001/photo-22.webp" },
    { f: "photo-23.webp", c: "bedroom", u: "/properties/castleford-5001/photo-23.webp" },
    { f: "photo-24.webp", c: "exterior-front", u: "/properties/castleford-5001/photo-24.webp" },
    { f: "photo-25.webp", c: "bedroom", u: "/properties/castleford-5001/photo-25.webp" },
    { f: "photo-26.webp", c: "bedroom", u: "/properties/castleford-5001/photo-26.webp" },
    { f: "photo-27.webp", c: "entrance", u: "/properties/castleford-5001/photo-27.webp" },
    { f: "photo-28.webp", c: "backyard", u: "/properties/castleford-5001/photo-28.webp" },
    { f: "photo-29.webp", c: "dining-room", u: "/properties/castleford-5001/photo-29.webp" },
    { f: "photo-3.webp", c: "living-room", u: "/properties/castleford-5001/photo-3.webp" },
    { f: "photo-30.webp", c: "yard", u: "/properties/castleford-5001/photo-30.webp" },
    { f: "photo-31.webp", c: "dining-room", u: "/properties/castleford-5001/photo-31.webp" },
    { f: "photo-32.webp", c: "living-room", u: "/properties/castleford-5001/photo-32.webp" },
    { f: "photo-33.webp", c: "kitchen", u: "/properties/castleford-5001/photo-33.webp" },
    { f: "photo-34.webp", c: "kitchen", u: "/properties/castleford-5001/photo-34.webp" },
    { f: "photo-35.webp", c: "kitchen", u: "/properties/castleford-5001/photo-35.webp" },
    { f: "photo-36.webp", c: "exterior-front", u: "/properties/castleford-5001/photo-36.webp" },
    { f: "photo-37.webp", c: "kitchen", u: "/properties/castleford-5001/photo-37.webp" },
    { f: "photo-38.webp", c: "kitchen", u: "/properties/castleford-5001/photo-38.webp" },
    { f: "photo-39.webp", c: "living-room", u: "/properties/castleford-5001/photo-39.webp" },
    { f: "photo-4.webp", c: "games-room", u: "/properties/castleford-5001/photo-4.webp" },
    { f: "photo-40.webp", c: "living-room", u: "/properties/castleford-5001/photo-40.webp" },
    { f: "photo-41.webp", c: "living-room", u: "/properties/castleford-5001/photo-41.webp" },
    { f: "photo-42.webp", c: "games-room", u: "/properties/castleford-5001/photo-42.webp" },
    { f: "photo-43.webp", c: "games-room", u: "/properties/castleford-5001/photo-43.webp" },
    { f: "photo-44.webp", c: "games-room", u: "/properties/castleford-5001/photo-44.webp" },
    { f: "photo-45.webp", c: "exterior-front", u: "/properties/castleford-5001/photo-45.webp" },
    { f: "photo-46.webp", c: "games-room", u: "/properties/castleford-5001/photo-46.webp" },
    { f: "photo-47.webp", c: "bathroom", u: "/properties/castleford-5001/photo-47.webp" },
    { f: "photo-48.webp", c: "covered-patio", u: "/properties/castleford-5001/photo-48.webp" },
    { f: "photo-49.webp", c: "bathroom", u: "/properties/castleford-5001/photo-49.webp" },
    { f: "photo-5.webp", c: "bedroom", u: "/properties/castleford-5001/photo-5.webp" },
    { f: "photo-50.webp", c: "covered-patio", u: "/properties/castleford-5001/photo-50.webp" },
    { f: "photo-51.webp", c: "patio", u: "/properties/castleford-5001/photo-51.webp" },
    { f: "photo-52.webp", c: "pool", u: "/properties/castleford-5001/photo-52.webp" },
    { f: "photo-53.webp", c: "pool", u: "/properties/castleford-5001/photo-53.webp" },
    { f: "photo-54.webp", c: "covered-patio", u: "/properties/castleford-5001/photo-54.webp" },
    { f: "photo-55.webp", c: "exterior-front", u: "/properties/castleford-5001/photo-55.webp" },
    { f: "photo-56.webp", c: "pool", u: "/properties/castleford-5001/photo-56.webp" },
    { f: "photo-57.webp", c: "exterior-front", u: "/properties/castleford-5001/photo-57.webp" },
    { f: "photo-58.webp", c: "exterior-front", u: "/properties/castleford-5001/photo-58.webp" },
    { f: "photo-59.webp", c: "bedroom", u: "/properties/castleford-5001/photo-59.webp" },
    { f: "photo-6.webp", c: "bedroom", u: "/properties/castleford-5001/photo-6.webp" },
    { f: "photo-60.webp", c: "master-bathroom", u: "/properties/castleford-5001/photo-60.webp" },
    { f: "photo-61.webp", c: "bathroom", u: "/properties/castleford-5001/photo-61.webp" },
    { f: "photo-62.webp", c: "bathroom", u: "/properties/castleford-5001/photo-62.webp" },
    { f: "photo-63.webp", c: "bedroom", u: "/properties/castleford-5001/photo-63.webp" },
    { f: "photo-64.webp", c: "master-bathroom", u: "/properties/castleford-5001/photo-64.webp" },
    { f: "photo-65.webp", c: "laundry", u: "/properties/castleford-5001/photo-65.webp" },
    { f: "photo-66.webp", c: "bedroom", u: "/properties/castleford-5001/photo-66.webp" },
    { f: "photo-7.webp", c: "bedroom", u: "/properties/castleford-5001/photo-7.webp" },
    { f: "photo-8.webp", c: "bedroom", u: "/properties/castleford-5001/photo-8.webp" },
    { f: "photo-9.webp", c: "bedroom", u: "/properties/castleford-5001/photo-9.webp" },
    { f: "pool-2.webp", c: "pool", u: "/properties/castleford-5001/pool-2.webp" },
    { f: "pool-3.webp", c: "pool", u: "/properties/castleford-5001/pool-3.webp" },
    { f: "pool-4.webp", c: "pool", u: "/properties/castleford-5001/pool-4.webp" },
    { f: "private-kitchen-2.webp", c: "kitchen", u: "/properties/castleford-5001/private-kitchen-2.webp" },
    { f: "private-kitchen-3.webp", c: "kitchen", u: "/properties/castleford-5001/private-kitchen-3.webp" },
    { f: "private-kitchen-4.webp", c: "kitchen", u: "/properties/castleford-5001/private-kitchen-4.webp" },
    { f: "private-kitchen-5.webp", c: "kitchen", u: "/properties/castleford-5001/private-kitchen-5.webp" },
    { f: "private-kitchen-6.webp", c: "kitchen", u: "/properties/castleford-5001/private-kitchen-6.webp" },
    { f: "private-kitchen.webp", c: "kitchen", u: "/properties/castleford-5001/private-kitchen.webp" },
    { f: "room-10.webp", c: "bedroom", u: "/properties/castleford-5001/room-10.webp" },
    { f: "room-11.webp", c: "bedroom", u: "/properties/castleford-5001/room-11.webp" },
    { f: "room-12.webp", c: "bedroom", u: "/properties/castleford-5001/room-12.webp" },
    { f: "room-13.webp", c: "bedroom", u: "/properties/castleford-5001/room-13.webp" },
    { f: "room-14.webp", c: "bedroom", u: "/properties/castleford-5001/room-14.webp" },
    { f: "room-15.webp", c: "bedroom", u: "/properties/castleford-5001/room-15.webp" },
    { f: "room-16.webp", c: "bedroom", u: "/properties/castleford-5001/room-16.webp" },
    { f: "room-17.webp", c: "bedroom", u: "/properties/castleford-5001/room-17.webp" },
    { f: "room-2.webp", c: "bedroom", u: "/properties/castleford-5001/room-2.webp" },
    { f: "room-3.webp", c: "bedroom", u: "/properties/castleford-5001/room-3.webp" },
    { f: "room-4.webp", c: "bedroom", u: "/properties/castleford-5001/room-4.webp" },
    { f: "room-5.webp", c: "bedroom", u: "/properties/castleford-5001/room-5.webp" },
    { f: "room-6.webp", c: "bedroom", u: "/properties/castleford-5001/room-6.webp" },
    { f: "room-7.webp", c: "bedroom", u: "/properties/castleford-5001/room-7.webp" },
    { f: "room-8.webp", c: "bedroom", u: "/properties/castleford-5001/room-8.webp" },
    { f: "room-9.webp", c: "bedroom", u: "/properties/castleford-5001/room-9.webp" },
    { f: "room.webp", c: "bedroom", u: "/properties/castleford-5001/room.webp" },
    { f: "terrace-patio.webp", c: "patio", u: "/properties/castleford-5001/terrace-patio.webp" },
  ],
  "chelsea-3210": [
    { f: "bathroom-2.webp", c: "bathroom", u: "/properties/chelsea-3210/bathroom-2.webp" },
    { f: "bathroom-3.webp", c: "bathroom", u: "/properties/chelsea-3210/bathroom-3.webp" },
    { f: "bathroom-4.webp", c: "bathroom", u: "/properties/chelsea-3210/bathroom-4.webp" },
    { f: "bathroom-5.webp", c: "bathroom", u: "/properties/chelsea-3210/bathroom-5.webp" },
    { f: "bathroom.webp", c: "bathroom", u: "/properties/chelsea-3210/bathroom.webp" },
    { f: "dining-2.webp", c: "dining-room", u: "/properties/chelsea-3210/dining-2.webp" },
    { f: "dining-3.webp", c: "dining-room", u: "/properties/chelsea-3210/dining-3.webp" },
    { f: "dining.webp", c: "dining-room", u: "/properties/chelsea-3210/dining.webp" },
    { f: "exterior-2.webp", c: "exterior-front", u: "/properties/chelsea-3210/exterior-2.webp" },
    { f: "exterior-3.webp", c: "exterior-front", u: "/properties/chelsea-3210/exterior-3.webp" },
    { f: "exterior-detail.webp", c: "exterior-front", u: "/properties/chelsea-3210/exterior-detail.webp" },
    { f: "interior.webp", c: "living-room", u: "/properties/chelsea-3210/interior.webp" },
    { f: "living-area-2.webp", c: "living-room", u: "/properties/chelsea-3210/living-area-2.webp" },
    { f: "living-area-3.webp", c: "living-room", u: "/properties/chelsea-3210/living-area-3.webp" },
    { f: "living-area-4.webp", c: "living-room", u: "/properties/chelsea-3210/living-area-4.webp" },
    { f: "living-area.webp", c: "living-room", u: "/properties/chelsea-3210/living-area.webp" },
    { f: "main.webp", c: "hero", u: "/properties/chelsea-3210/main.webp" },
    { f: "outdoor-dining-2.webp", c: "outdoor-dining", u: "/properties/chelsea-3210/outdoor-dining-2.webp" },
    { f: "outdoor-dining-3.webp", c: "outdoor-dining", u: "/properties/chelsea-3210/outdoor-dining-3.webp" },
    { f: "outdoor-dining.webp", c: "outdoor-dining", u: "/properties/chelsea-3210/outdoor-dining.webp" },
    { f: "private-kitchen-2.webp", c: "kitchen", u: "/properties/chelsea-3210/private-kitchen-2.webp" },
    { f: "private-kitchen-3.webp", c: "kitchen", u: "/properties/chelsea-3210/private-kitchen-3.webp" },
    { f: "private-kitchen-4.webp", c: "kitchen", u: "/properties/chelsea-3210/private-kitchen-4.webp" },
    { f: "private-kitchen.webp", c: "kitchen", u: "/properties/chelsea-3210/private-kitchen.webp" },
    { f: "property-grounds.webp", c: "yard", u: "/properties/chelsea-3210/property-grounds.webp" },
    { f: "room-10.webp", c: "bedroom", u: "/properties/chelsea-3210/room-10.webp" },
    { f: "room-2.webp", c: "bedroom", u: "/properties/chelsea-3210/room-2.webp" },
    { f: "room-3.webp", c: "bedroom", u: "/properties/chelsea-3210/room-3.webp" },
    { f: "room-4.webp", c: "bedroom", u: "/properties/chelsea-3210/room-4.webp" },
    { f: "room-5.webp", c: "bedroom", u: "/properties/chelsea-3210/room-5.webp" },
    { f: "room-6.webp", c: "bedroom", u: "/properties/chelsea-3210/room-6.webp" },
    { f: "room-7.webp", c: "bedroom", u: "/properties/chelsea-3210/room-7.webp" },
    { f: "room-8.webp", c: "bedroom", u: "/properties/chelsea-3210/room-8.webp" },
    { f: "room-9.webp", c: "bedroom", u: "/properties/chelsea-3210/room-9.webp" },
    { f: "room.webp", c: "bedroom", u: "/properties/chelsea-3210/room.webp" },
    { f: "terrace-patio.webp", c: "patio", u: "/properties/chelsea-3210/terrace-patio.webp" },
  ],
  "douglas-2800": [
    { f: "main.webp", c: "hero", u: "/properties/douglas-2800/main.webp" },
    { f: "photo-1.webp", c: "exterior-front", u: "/properties/douglas-2800/photo-1.webp" },
    { f: "photo-10.webp", c: "bathroom", u: "/properties/douglas-2800/photo-10.webp" },
    { f: "photo-11.webp", c: "kitchen", u: "/properties/douglas-2800/photo-11.webp" },
    { f: "photo-12.webp", c: "exterior-front", u: "/properties/douglas-2800/photo-12.webp" },
    { f: "photo-13.webp", c: "living-room", u: "/properties/douglas-2800/photo-13.webp" },
    { f: "photo-14.webp", c: "kitchen", u: "/properties/douglas-2800/photo-14.webp" },
    { f: "photo-15.webp", c: "kitchen", u: "/properties/douglas-2800/photo-15.webp" },
    { f: "photo-16.webp", c: "exterior-front", u: "/properties/douglas-2800/photo-16.webp" },
    { f: "photo-17.webp", c: "kitchen", u: "/properties/douglas-2800/photo-17.webp" },
    { f: "photo-18.webp", c: "bedroom", u: "/properties/douglas-2800/photo-18.webp" },
    { f: "photo-19.webp", c: "backyard", u: "/properties/douglas-2800/photo-19.webp" },
    { f: "photo-2.webp", c: "living-room", u: "/properties/douglas-2800/photo-2.webp" },
    { f: "photo-20.webp", c: "living-room", u: "/properties/douglas-2800/photo-20.webp" },
    { f: "photo-21.webp", c: "living-room", u: "/properties/douglas-2800/photo-21.webp" },
    { f: "photo-22.webp", c: "dining-room", u: "/properties/douglas-2800/photo-22.webp" },
    { f: "photo-23.webp", c: "bedroom", u: "/properties/douglas-2800/photo-23.webp" },
    { f: "photo-24.webp", c: "bedroom", u: "/properties/douglas-2800/photo-24.webp" },
    { f: "photo-25.webp", c: "laundry", u: "/properties/douglas-2800/photo-25.webp" },
    { f: "photo-26.webp", c: "exterior-front", u: "/properties/douglas-2800/photo-26.webp" },
    { f: "photo-27.webp", c: "bedroom", u: "/properties/douglas-2800/photo-27.webp" },
    { f: "photo-28.webp", c: "bedroom", u: "/properties/douglas-2800/photo-28.webp" },
    { f: "photo-29.webp", c: "living-room", u: "/properties/douglas-2800/photo-29.webp" },
    { f: "photo-3.webp", c: "kitchen", u: "/properties/douglas-2800/photo-3.webp" },
    { f: "photo-30.webp", c: "living-room", u: "/properties/douglas-2800/photo-30.webp" },
    { f: "photo-31.webp", c: "kitchen", u: "/properties/douglas-2800/photo-31.webp" },
    { f: "photo-32.webp", c: "kitchen", u: "/properties/douglas-2800/photo-32.webp" },
    { f: "photo-33.webp", c: "kitchen", u: "/properties/douglas-2800/photo-33.webp" },
    { f: "photo-34.webp", c: "kitchen", u: "/properties/douglas-2800/photo-34.webp" },
    { f: "photo-35.webp", c: "bedroom", u: "/properties/douglas-2800/photo-35.webp" },
    { f: "photo-36.webp", c: "kitchen", u: "/properties/douglas-2800/photo-36.webp" },
    { f: "photo-37.webp", c: "bedroom", u: "/properties/douglas-2800/photo-37.webp" },
    { f: "photo-38.webp", c: "bedroom", u: "/properties/douglas-2800/photo-38.webp" },
    { f: "photo-39.webp", c: "bedroom", u: "/properties/douglas-2800/photo-39.webp" },
    { f: "photo-4.webp", c: "backyard", u: "/properties/douglas-2800/photo-4.webp" },
    { f: "photo-40.webp", c: "exterior-front", u: "/properties/douglas-2800/photo-40.webp" },
    { f: "photo-41.webp", c: "kitchen", u: "/properties/douglas-2800/photo-41.webp" },
    { f: "photo-42.webp", c: "bathroom", u: "/properties/douglas-2800/photo-42.webp" },
    { f: "photo-43.webp", c: "patio", u: "/properties/douglas-2800/photo-43.webp" },
    { f: "photo-44.webp", c: "bedroom", u: "/properties/douglas-2800/photo-44.webp" },
    { f: "photo-45.webp", c: "bathroom", u: "/properties/douglas-2800/photo-45.webp" },
    { f: "photo-46.webp", c: "kitchen", u: "/properties/douglas-2800/photo-46.webp" },
    { f: "photo-47.webp", c: "dining-room", u: "/properties/douglas-2800/photo-47.webp" },
    { f: "photo-48.webp", c: "bathroom", u: "/properties/douglas-2800/photo-48.webp" },
    { f: "photo-49.webp", c: "bathroom", u: "/properties/douglas-2800/photo-49.webp" },
    { f: "photo-5.webp", c: "kitchen", u: "/properties/douglas-2800/photo-5.webp" },
    { f: "photo-50.webp", c: "bathroom", u: "/properties/douglas-2800/photo-50.webp" },
    { f: "photo-51.webp", c: "bedroom", u: "/properties/douglas-2800/photo-51.webp" },
    { f: "photo-52.webp", c: "bathroom", u: "/properties/douglas-2800/photo-52.webp" },
    { f: "photo-6.webp", c: "bedroom", u: "/properties/douglas-2800/photo-6.webp" },
    { f: "photo-7.webp", c: "exterior-front", u: "/properties/douglas-2800/photo-7.webp" },
    { f: "photo-8.webp", c: "kitchen", u: "/properties/douglas-2800/photo-8.webp" },
    { f: "photo-9.webp", c: "backyard", u: "/properties/douglas-2800/photo-9.webp" },
  ],
  "garfield-2702": [
    { f: "main.webp", c: "hero", u: "/properties/garfield-2702/main.webp" },
    { f: "photo-1.webp", c: "dining-room", u: "/properties/garfield-2702/photo-1.webp" },
    { f: "photo-10.webp", c: "dining-room", u: "/properties/garfield-2702/photo-10.webp" },
    { f: "photo-11.webp", c: "exterior-back", u: "/properties/garfield-2702/photo-11.webp" },
    { f: "photo-12.webp", c: "exterior-front", u: "/properties/garfield-2702/photo-12.webp" },
    { f: "photo-13.webp", c: "patio", u: "/properties/garfield-2702/photo-13.webp" },
    { f: "photo-14.webp", c: "bedroom", u: "/properties/garfield-2702/photo-14.webp" },
    { f: "photo-15.webp", c: "master-bathroom", u: "/properties/garfield-2702/photo-15.webp" },
    { f: "photo-16.webp", c: "kitchen", u: "/properties/garfield-2702/photo-16.webp" },
    { f: "photo-17.webp", c: "backyard", u: "/properties/garfield-2702/photo-17.webp" },
    { f: "photo-18.webp", c: "living-room", u: "/properties/garfield-2702/photo-18.webp" },
    { f: "photo-19.webp", c: "covered-patio", u: "/properties/garfield-2702/photo-19.webp" },
    { f: "photo-2.webp", c: "bedroom", u: "/properties/garfield-2702/photo-2.webp" },
    { f: "photo-20.webp", c: "living-room", u: "/properties/garfield-2702/photo-20.webp" },
    { f: "photo-21.webp", c: "living-room", u: "/properties/garfield-2702/photo-21.webp" },
    { f: "photo-22.webp", c: "living-room", u: "/properties/garfield-2702/photo-22.webp" },
    { f: "photo-23.webp", c: "living-room", u: "/properties/garfield-2702/photo-23.webp" },
    { f: "photo-24.webp", c: "dining-room", u: "/properties/garfield-2702/photo-24.webp" },
    { f: "photo-25.webp", c: "entrance", u: "/properties/garfield-2702/photo-25.webp" },
    { f: "photo-26.webp", c: "living-room", u: "/properties/garfield-2702/photo-26.webp" },
    { f: "photo-27.webp", c: "bathroom", u: "/properties/garfield-2702/photo-27.webp" },
    { f: "photo-28.webp", c: "bedroom", u: "/properties/garfield-2702/photo-28.webp" },
    { f: "photo-29.webp", c: "bathroom", u: "/properties/garfield-2702/photo-29.webp" },
    { f: "photo-3.webp", c: "patio", u: "/properties/garfield-2702/photo-3.webp" },
    { f: "photo-30.webp", c: "bathroom", u: "/properties/garfield-2702/photo-30.webp" },
    { f: "photo-31.webp", c: "dining-room", u: "/properties/garfield-2702/photo-31.webp" },
    { f: "photo-32.webp", c: "dining-room", u: "/properties/garfield-2702/photo-32.webp" },
    { f: "photo-33.webp", c: "dining-room", u: "/properties/garfield-2702/photo-33.webp" },
    { f: "photo-34.webp", c: "dining-room", u: "/properties/garfield-2702/photo-34.webp" },
    { f: "photo-35.webp", c: "kitchen", u: "/properties/garfield-2702/photo-35.webp" },
    { f: "photo-36.webp", c: "bedroom", u: "/properties/garfield-2702/photo-36.webp" },
    { f: "photo-37.webp", c: "kitchen", u: "/properties/garfield-2702/photo-37.webp" },
    { f: "photo-38.webp", c: "kitchen", u: "/properties/garfield-2702/photo-38.webp" },
    { f: "photo-39.webp", c: "kitchen", u: "/properties/garfield-2702/photo-39.webp" },
    { f: "photo-4.webp", c: "living-room", u: "/properties/garfield-2702/photo-4.webp" },
    { f: "photo-40.webp", c: "kitchen", u: "/properties/garfield-2702/photo-40.webp" },
    { f: "photo-41.webp", c: "kitchen", u: "/properties/garfield-2702/photo-41.webp" },
    { f: "photo-42.webp", c: "kitchen", u: "/properties/garfield-2702/photo-42.webp" },
    { f: "photo-43.webp", c: "kitchen", u: "/properties/garfield-2702/photo-43.webp" },
    { f: "photo-44.webp", c: "laundry", u: "/properties/garfield-2702/photo-44.webp" },
    { f: "photo-45.webp", c: "bedroom", u: "/properties/garfield-2702/photo-45.webp" },
    { f: "photo-46.webp", c: "bedroom", u: "/properties/garfield-2702/photo-46.webp" },
    { f: "photo-47.webp", c: "bedroom", u: "/properties/garfield-2702/photo-47.webp" },
    { f: "photo-48.webp", c: "bathroom", u: "/properties/garfield-2702/photo-48.webp" },
    { f: "photo-49.webp", c: "bathroom", u: "/properties/garfield-2702/photo-49.webp" },
    { f: "photo-5.webp", c: "kitchen", u: "/properties/garfield-2702/photo-5.webp" },
    { f: "photo-50.webp", c: "master-bedroom", u: "/properties/garfield-2702/photo-50.webp" },
    { f: "photo-51.webp", c: "master-bedroom", u: "/properties/garfield-2702/photo-51.webp" },
    { f: "photo-52.webp", c: "master-bedroom", u: "/properties/garfield-2702/photo-52.webp" },
    { f: "photo-53.webp", c: "master-bedroom", u: "/properties/garfield-2702/photo-53.webp" },
    { f: "photo-54.webp", c: "master-bathroom", u: "/properties/garfield-2702/photo-54.webp" },
    { f: "photo-55.webp", c: "master-bedroom", u: "/properties/garfield-2702/photo-55.webp" },
    { f: "photo-56.webp", c: "master-bathroom", u: "/properties/garfield-2702/photo-56.webp" },
    { f: "photo-57.webp", c: "master-bathroom", u: "/properties/garfield-2702/photo-57.webp" },
    { f: "photo-58.webp", c: "exterior-front", u: "/properties/garfield-2702/photo-58.webp" },
    { f: "photo-59.webp", c: "master-bathroom", u: "/properties/garfield-2702/photo-59.webp" },
    { f: "photo-6.webp", c: "kitchen", u: "/properties/garfield-2702/photo-6.webp" },
    { f: "photo-60.webp", c: "exterior-front", u: "/properties/garfield-2702/photo-60.webp" },
    { f: "photo-61.webp", c: "exterior-back", u: "/properties/garfield-2702/photo-61.webp" },
    { f: "photo-62.webp", c: "exterior-front", u: "/properties/garfield-2702/photo-62.webp" },
    { f: "photo-63.webp", c: "exterior-back", u: "/properties/garfield-2702/photo-63.webp" },
    { f: "photo-64.webp", c: "covered-patio", u: "/properties/garfield-2702/photo-64.webp" },
    { f: "photo-65.webp", c: "hot-tub", u: "/properties/garfield-2702/photo-65.webp" },
    { f: "photo-66.webp", c: "hot-tub", u: "/properties/garfield-2702/photo-66.webp" },
    { f: "photo-7.webp", c: "exterior-front", u: "/properties/garfield-2702/photo-7.webp" },
    { f: "photo-8.webp", c: "master-bedroom", u: "/properties/garfield-2702/photo-8.webp" },
    { f: "photo-9.webp", c: "backyard", u: "/properties/garfield-2702/photo-9.webp" },
  ],
  "haynes-2802": [
    { f: "main.png", c: "hero", u: "/properties/haynes-2802/main.png" },
  ],
  "lincoln-green-5055": [
    { f: "bathroom-10.webp", c: "bathroom", u: "/properties/lincoln-green-5055/bathroom-10.webp" },
    { f: "bathroom-11.webp", c: "bathroom", u: "/properties/lincoln-green-5055/bathroom-11.webp" },
    { f: "bathroom-2.webp", c: "bathroom", u: "/properties/lincoln-green-5055/bathroom-2.webp" },
    { f: "bathroom-3.webp", c: "bathroom", u: "/properties/lincoln-green-5055/bathroom-3.webp" },
    { f: "bathroom-4.webp", c: "bathroom", u: "/properties/lincoln-green-5055/bathroom-4.webp" },
    { f: "bathroom-5.webp", c: "bathroom", u: "/properties/lincoln-green-5055/bathroom-5.webp" },
    { f: "bathroom-6.webp", c: "bathroom", u: "/properties/lincoln-green-5055/bathroom-6.webp" },
    { f: "bathroom-7.webp", c: "bathroom", u: "/properties/lincoln-green-5055/bathroom-7.webp" },
    { f: "bathroom-8.webp", c: "bathroom", u: "/properties/lincoln-green-5055/bathroom-8.webp" },
    { f: "bathroom-9.webp", c: "bathroom", u: "/properties/lincoln-green-5055/bathroom-9.webp" },
    { f: "bathroom.webp", c: "bathroom", u: "/properties/lincoln-green-5055/bathroom.webp" },
    { f: "childrens-area.webp", c: "childrens-area", u: "/properties/lincoln-green-5055/childrens-area.webp" },
    { f: "dining-2.webp", c: "dining-room", u: "/properties/lincoln-green-5055/dining-2.webp" },
    { f: "dining-3.webp", c: "dining-room", u: "/properties/lincoln-green-5055/dining-3.webp" },
    { f: "dining-4.webp", c: "dining-room", u: "/properties/lincoln-green-5055/dining-4.webp" },
    { f: "dining-5.webp", c: "dining-room", u: "/properties/lincoln-green-5055/dining-5.webp" },
    { f: "dining-6.webp", c: "dining-room", u: "/properties/lincoln-green-5055/dining-6.webp" },
    { f: "dining-7.webp", c: "dining-room", u: "/properties/lincoln-green-5055/dining-7.webp" },
    { f: "dining-8.webp", c: "dining-room", u: "/properties/lincoln-green-5055/dining-8.webp" },
    { f: "dining.webp", c: "dining-room", u: "/properties/lincoln-green-5055/dining.webp" },
    { f: "exterior-2.webp", c: "exterior-front", u: "/properties/lincoln-green-5055/exterior-2.webp" },
    { f: "interior-2.webp", c: "living-room", u: "/properties/lincoln-green-5055/interior-2.webp" },
    { f: "interior-3.webp", c: "living-room", u: "/properties/lincoln-green-5055/interior-3.webp" },
    { f: "interior-4.webp", c: "living-room", u: "/properties/lincoln-green-5055/interior-4.webp" },
    { f: "interior-5.webp", c: "living-room", u: "/properties/lincoln-green-5055/interior-5.webp" },
    { f: "interior-6.webp", c: "living-room", u: "/properties/lincoln-green-5055/interior-6.webp" },
    { f: "interior-7.webp", c: "living-room", u: "/properties/lincoln-green-5055/interior-7.webp" },
    { f: "interior-8.webp", c: "living-room", u: "/properties/lincoln-green-5055/interior-8.webp" },
    { f: "interior-9.webp", c: "living-room", u: "/properties/lincoln-green-5055/interior-9.webp" },
    { f: "interior.webp", c: "living-room", u: "/properties/lincoln-green-5055/interior.webp" },
    { f: "living-area-2.webp", c: "living-room", u: "/properties/lincoln-green-5055/living-area-2.webp" },
    { f: "living-area-3.webp", c: "living-room", u: "/properties/lincoln-green-5055/living-area-3.webp" },
    { f: "living-area-4.webp", c: "living-room", u: "/properties/lincoln-green-5055/living-area-4.webp" },
    { f: "living-area-5.webp", c: "living-room", u: "/properties/lincoln-green-5055/living-area-5.webp" },
    { f: "living-area-6.webp", c: "living-room", u: "/properties/lincoln-green-5055/living-area-6.webp" },
    { f: "living-area-7.webp", c: "living-room", u: "/properties/lincoln-green-5055/living-area-7.webp" },
    { f: "living-area-8.webp", c: "living-room", u: "/properties/lincoln-green-5055/living-area-8.webp" },
    { f: "living-area-9.webp", c: "living-room", u: "/properties/lincoln-green-5055/living-area-9.webp" },
    { f: "living-area.webp", c: "living-room", u: "/properties/lincoln-green-5055/living-area.webp" },
    { f: "main.webp", c: "hero", u: "/properties/lincoln-green-5055/main.webp" },
    { f: "outdoor-dining-2.webp", c: "outdoor-dining", u: "/properties/lincoln-green-5055/outdoor-dining-2.webp" },
    { f: "outdoor-dining-3.webp", c: "outdoor-dining", u: "/properties/lincoln-green-5055/outdoor-dining-3.webp" },
    { f: "outdoor-dining.webp", c: "outdoor-dining", u: "/properties/lincoln-green-5055/outdoor-dining.webp" },
    { f: "pool-2.webp", c: "pool", u: "/properties/lincoln-green-5055/pool-2.webp" },
    { f: "pool-3.webp", c: "pool", u: "/properties/lincoln-green-5055/pool-3.webp" },
    { f: "pool-4.webp", c: "pool", u: "/properties/lincoln-green-5055/pool-4.webp" },
    { f: "pool-5.webp", c: "pool", u: "/properties/lincoln-green-5055/pool-5.webp" },
    { f: "pool.webp", c: "pool", u: "/properties/lincoln-green-5055/pool.webp" },
    { f: "private-kitchen-2.webp", c: "kitchen", u: "/properties/lincoln-green-5055/private-kitchen-2.webp" },
    { f: "private-kitchen-3.webp", c: "kitchen", u: "/properties/lincoln-green-5055/private-kitchen-3.webp" },
    { f: "private-kitchen-4.webp", c: "kitchen", u: "/properties/lincoln-green-5055/private-kitchen-4.webp" },
    { f: "private-kitchen-5.webp", c: "kitchen", u: "/properties/lincoln-green-5055/private-kitchen-5.webp" },
    { f: "private-kitchen-6.webp", c: "kitchen", u: "/properties/lincoln-green-5055/private-kitchen-6.webp" },
    { f: "private-kitchen-7.webp", c: "kitchen", u: "/properties/lincoln-green-5055/private-kitchen-7.webp" },
    { f: "private-kitchen.webp", c: "kitchen", u: "/properties/lincoln-green-5055/private-kitchen.webp" },
    { f: "property-grounds-2.webp", c: "yard", u: "/properties/lincoln-green-5055/property-grounds-2.webp" },
    { f: "property-grounds-3.webp", c: "yard", u: "/properties/lincoln-green-5055/property-grounds-3.webp" },
    { f: "property-grounds.webp", c: "yard", u: "/properties/lincoln-green-5055/property-grounds.webp" },
    { f: "room-10.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-10.webp" },
    { f: "room-11.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-11.webp" },
    { f: "room-12.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-12.webp" },
    { f: "room-13.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-13.webp" },
    { f: "room-14.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-14.webp" },
    { f: "room-15.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-15.webp" },
    { f: "room-16.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-16.webp" },
    { f: "room-17.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-17.webp" },
    { f: "room-18.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-18.webp" },
    { f: "room-19.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-19.webp" },
    { f: "room-2.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-2.webp" },
    { f: "room-20.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-20.webp" },
    { f: "room-21.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-21.webp" },
    { f: "room-22.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-22.webp" },
    { f: "room-3.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-3.webp" },
    { f: "room-4.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-4.webp" },
    { f: "room-5.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-5.webp" },
    { f: "room-6.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-6.webp" },
    { f: "room-7.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-7.webp" },
    { f: "room-8.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-8.webp" },
    { f: "room-9.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room-9.webp" },
    { f: "room.webp", c: "bedroom", u: "/properties/lincoln-green-5055/room.webp" },
    { f: "spa.webp", c: "spa", u: "/properties/lincoln-green-5055/spa.webp" },
    { f: "terrace-patio-2.webp", c: "patio", u: "/properties/lincoln-green-5055/terrace-patio-2.webp" },
    { f: "terrace-patio-3.webp", c: "patio", u: "/properties/lincoln-green-5055/terrace-patio-3.webp" },
    { f: "terrace-patio.webp", c: "patio", u: "/properties/lincoln-green-5055/terrace-patio.webp" },
  ],
  "monterrey-1605": [
    { f: "main.webp", c: "hero", u: "/properties/monterrey-1605/main.webp" },
    { f: "photo-1.webp", c: "bedroom", u: "/properties/monterrey-1605/photo-1.webp" },
    { f: "photo-10.webp", c: "kitchen", u: "/properties/monterrey-1605/photo-10.webp" },
    { f: "photo-11.webp", c: "living-room", u: "/properties/monterrey-1605/photo-11.webp" },
    { f: "photo-12.webp", c: "garage", u: "/properties/monterrey-1605/photo-12.webp" },
    { f: "photo-13.webp", c: "kitchen", u: "/properties/monterrey-1605/photo-13.webp" },
    { f: "photo-14.webp", c: "living-room", u: "/properties/monterrey-1605/photo-14.webp" },
    { f: "photo-15.webp", c: "bedroom", u: "/properties/monterrey-1605/photo-15.webp" },
    { f: "photo-16.webp", c: "exterior-front", u: "/properties/monterrey-1605/photo-16.webp" },
    { f: "photo-17.webp", c: "covered-patio", u: "/properties/monterrey-1605/photo-17.webp" },
    { f: "photo-18.webp", c: "bathroom", u: "/properties/monterrey-1605/photo-18.webp" },
    { f: "photo-19.webp", c: "bedroom", u: "/properties/monterrey-1605/photo-19.webp" },
    { f: "photo-2.webp", c: "kitchen", u: "/properties/monterrey-1605/photo-2.webp" },
    { f: "photo-20.webp", c: "bedroom", u: "/properties/monterrey-1605/photo-20.webp" },
    { f: "photo-21.webp", c: "exterior-front", u: "/properties/monterrey-1605/photo-21.webp" },
    { f: "photo-22.webp", c: "living-room", u: "/properties/monterrey-1605/photo-22.webp" },
    { f: "photo-23.webp", c: "master-bedroom", u: "/properties/monterrey-1605/photo-23.webp" },
    { f: "photo-24.webp", c: "covered-patio", u: "/properties/monterrey-1605/photo-24.webp" },
    { f: "photo-25.webp", c: "dining-room", u: "/properties/monterrey-1605/photo-25.webp" },
    { f: "photo-26.webp", c: "bedroom", u: "/properties/monterrey-1605/photo-26.webp" },
    { f: "photo-3.webp", c: "covered-patio", u: "/properties/monterrey-1605/photo-3.webp" },
    { f: "photo-4.webp", c: "bathroom", u: "/properties/monterrey-1605/photo-4.webp" },
    { f: "photo-5.webp", c: "bedroom", u: "/properties/monterrey-1605/photo-5.webp" },
    { f: "photo-6.webp", c: "laundry", u: "/properties/monterrey-1605/photo-6.webp" },
    { f: "photo-7.webp", c: "kitchen", u: "/properties/monterrey-1605/photo-7.webp" },
    { f: "photo-8.webp", c: "kitchen", u: "/properties/monterrey-1605/photo-8.webp" },
    { f: "photo-9.webp", c: "bedroom", u: "/properties/monterrey-1605/photo-9.webp" },
  ],
  "shandon-3528": [
    { f: "main.webp", c: "hero", u: "/properties/shandon-3528/main.webp" },
    { f: "photo-1.webp", c: "exterior-front", u: "/properties/shandon-3528/photo-1.webp" },
    { f: "photo-10.webp", c: "covered-patio", u: "/properties/shandon-3528/photo-10.webp" },
    { f: "photo-11.webp", c: "covered-patio", u: "/properties/shandon-3528/photo-11.webp" },
    { f: "photo-12.webp", c: "covered-patio", u: "/properties/shandon-3528/photo-12.webp" },
    { f: "photo-13.webp", c: "covered-patio", u: "/properties/shandon-3528/photo-13.webp" },
    { f: "photo-14.webp", c: "pool", u: "/properties/shandon-3528/photo-14.webp" },
    { f: "photo-15.webp", c: "pool", u: "/properties/shandon-3528/photo-15.webp" },
    { f: "photo-16.webp", c: "pool", u: "/properties/shandon-3528/photo-16.webp" },
    { f: "photo-17.webp", c: "pool", u: "/properties/shandon-3528/photo-17.webp" },
    { f: "photo-18.webp", c: "pool", u: "/properties/shandon-3528/photo-18.webp" },
    { f: "photo-19.webp", c: "pool", u: "/properties/shandon-3528/photo-19.webp" },
    { f: "photo-2.webp", c: "bedroom", u: "/properties/shandon-3528/photo-2.webp" },
    { f: "photo-20.webp", c: "bedroom", u: "/properties/shandon-3528/photo-20.webp" },
    { f: "photo-21.webp", c: "bedroom", u: "/properties/shandon-3528/photo-21.webp" },
    { f: "photo-22.webp", c: "bathroom", u: "/properties/shandon-3528/photo-22.webp" },
    { f: "photo-23.webp", c: "bathroom", u: "/properties/shandon-3528/photo-23.webp" },
    { f: "photo-24.webp", c: "bathroom", u: "/properties/shandon-3528/photo-24.webp" },
    { f: "photo-25.webp", c: "bathroom", u: "/properties/shandon-3528/photo-25.webp" },
    { f: "photo-26.webp", c: "bathroom", u: "/properties/shandon-3528/photo-26.webp" },
    { f: "photo-27.webp", c: "bedroom", u: "/properties/shandon-3528/photo-27.webp" },
    { f: "photo-28.webp", c: "bathroom", u: "/properties/shandon-3528/photo-28.webp" },
    { f: "photo-29.webp", c: "bedroom", u: "/properties/shandon-3528/photo-29.webp" },
    { f: "photo-3.webp", c: "exterior-front", u: "/properties/shandon-3528/photo-3.webp" },
    { f: "photo-30.webp", c: "bedroom", u: "/properties/shandon-3528/photo-30.webp" },
    { f: "photo-31.webp", c: "hallway", u: "/properties/shandon-3528/photo-31.webp" },
    { f: "photo-32.webp", c: "hallway", u: "/properties/shandon-3528/photo-32.webp" },
    { f: "photo-33.webp", c: "living-room", u: "/properties/shandon-3528/photo-33.webp" },
    { f: "photo-34.webp", c: "living-room", u: "/properties/shandon-3528/photo-34.webp" },
    { f: "photo-35.webp", c: "living-room", u: "/properties/shandon-3528/photo-35.webp" },
    { f: "photo-36.webp", c: "living-room", u: "/properties/shandon-3528/photo-36.webp" },
    { f: "photo-37.webp", c: "living-room", u: "/properties/shandon-3528/photo-37.webp" },
    { f: "photo-38.webp", c: "kitchen", u: "/properties/shandon-3528/photo-38.webp" },
    { f: "photo-39.webp", c: "kitchen", u: "/properties/shandon-3528/photo-39.webp" },
    { f: "photo-4.webp", c: "bedroom", u: "/properties/shandon-3528/photo-4.webp" },
    { f: "photo-40.webp", c: "kitchen", u: "/properties/shandon-3528/photo-40.webp" },
    { f: "photo-41.webp", c: "kitchen", u: "/properties/shandon-3528/photo-41.webp" },
    { f: "photo-42.webp", c: "kitchen", u: "/properties/shandon-3528/photo-42.webp" },
    { f: "photo-43.webp", c: "kitchen", u: "/properties/shandon-3528/photo-43.webp" },
    { f: "photo-44.webp", c: "kitchen", u: "/properties/shandon-3528/photo-44.webp" },
    { f: "photo-45.webp", c: "kitchen", u: "/properties/shandon-3528/photo-45.webp" },
    { f: "photo-46.webp", c: "dining-room", u: "/properties/shandon-3528/photo-46.webp" },
    { f: "photo-47.webp", c: "kitchen", u: "/properties/shandon-3528/photo-47.webp" },
    { f: "photo-48.webp", c: "kitchen", u: "/properties/shandon-3528/photo-48.webp" },
    { f: "photo-49.webp", c: "kitchen", u: "/properties/shandon-3528/photo-49.webp" },
    { f: "photo-5.webp", c: "exterior-front", u: "/properties/shandon-3528/photo-5.webp" },
    { f: "photo-50.webp", c: "kitchen", u: "/properties/shandon-3528/photo-50.webp" },
    { f: "photo-51.webp", c: "living-room", u: "/properties/shandon-3528/photo-51.webp" },
    { f: "photo-6.webp", c: "bedroom", u: "/properties/shandon-3528/photo-6.webp" },
    { f: "photo-7.webp", c: "exterior-front", u: "/properties/shandon-3528/photo-7.webp" },
    { f: "photo-8.webp", c: "exterior-front", u: "/properties/shandon-3528/photo-8.webp" },
    { f: "photo-9.webp", c: "entrance", u: "/properties/shandon-3528/photo-9.webp" },
  ],
  "storey-4801": [
    { f: "image-01.webp", c: "exterior-front", u: "/properties/storey-4801/image-01.webp" },
    { f: "image-02.webp", c: "exterior-front", u: "/properties/storey-4801/image-02.webp" },
    { f: "image-03.webp", c: "laundry", u: "/properties/storey-4801/image-03.webp" },
    { f: "image-04.webp", c: "bedroom", u: "/properties/storey-4801/image-04.webp" },
    { f: "image-05.webp", c: "master-bedroom", u: "/properties/storey-4801/image-05.webp" },
    { f: "image-06.webp", c: "covered-patio", u: "/properties/storey-4801/image-06.webp" },
    { f: "image-07.webp", c: "kitchen", u: "/properties/storey-4801/image-07.webp" },
    { f: "image-08.webp", c: "bathroom", u: "/properties/storey-4801/image-08.webp" },
    { f: "image-09.webp", c: "living-room", u: "/properties/storey-4801/image-09.webp" },
    { f: "image-10.webp", c: "kitchen", u: "/properties/storey-4801/image-10.webp" },
    { f: "image-11.webp", c: "bathroom", u: "/properties/storey-4801/image-11.webp" },
    { f: "image-12.webp", c: "bedroom", u: "/properties/storey-4801/image-12.webp" },
    { f: "image-13.webp", c: "living-room", u: "/properties/storey-4801/image-13.webp" },
    { f: "image-14.webp", c: "bathroom", u: "/properties/storey-4801/image-14.webp" },
    { f: "image-15.webp", c: "bedroom", u: "/properties/storey-4801/image-15.webp" },
    { f: "image-16.webp", c: "dining-room", u: "/properties/storey-4801/image-16.webp" },
    { f: "image-17.webp", c: "bathroom", u: "/properties/storey-4801/image-17.webp" },
    { f: "image-18.webp", c: "exterior-back", u: "/properties/storey-4801/image-18.webp" },
    { f: "image-19.webp", c: "bedroom", u: "/properties/storey-4801/image-19.webp" },
    { f: "image-20.webp", c: "dining-room", u: "/properties/storey-4801/image-20.webp" },
    { f: "image-21.webp", c: "living-room", u: "/properties/storey-4801/image-21.webp" },
    { f: "image-22.webp", c: "bedroom", u: "/properties/storey-4801/image-22.webp" },
    { f: "image-23.webp", c: "exterior-front", u: "/properties/storey-4801/image-23.webp" },
    { f: "image-24.webp", c: "living-room", u: "/properties/storey-4801/image-24.webp" },
    { f: "image-25.webp", c: "bedroom", u: "/properties/storey-4801/image-25.webp" },
    { f: "image-26.webp", c: "bedroom", u: "/properties/storey-4801/image-26.webp" },
    { f: "image-27.webp", c: "kitchen", u: "/properties/storey-4801/image-27.webp" },
    { f: "image-28.webp", c: "dining-room", u: "/properties/storey-4801/image-28.webp" },
    { f: "image-29.webp", c: "bedroom", u: "/properties/storey-4801/image-29.webp" },
    { f: "image-30.webp", c: "bedroom", u: "/properties/storey-4801/image-30.webp" },
    { f: "image-31.webp", c: "covered-patio", u: "/properties/storey-4801/image-31.webp" },
    { f: "image-32.webp", c: "backyard", u: "/properties/storey-4801/image-32.webp" },
    { f: "image-33.webp", c: "bedroom", u: "/properties/storey-4801/image-33.webp" },
    { f: "image-34.webp", c: "bedroom", u: "/properties/storey-4801/image-34.webp" },
    { f: "image-35.webp", c: "exterior-front", u: "/properties/storey-4801/image-35.webp" },
    { f: "image-36.webp", c: "exterior-front", u: "/properties/storey-4801/image-36.webp" },
    { f: "main.webp", c: "hero", u: "/properties/storey-4801/main.webp" },
  ],
};

const CATEGORY_ORDER = [
  "hero", "exterior-front", "exterior-back", "living-room", "kitchen",
  "dining-room", "master-bedroom", "bedroom", "master-bathroom", "bathroom",
  "games-room", "pool", "hot-tub", "patio", "covered-patio",
  "outdoor-dining", "yard", "backyard", "garage", "laundry",
  "entrance", "hallway", "office", "unknown",
];

function prettyCategory(c: string): string {
  return c.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
}

function prettyAlt(propertyId: string, category: string, index: number): string {
  const propName = propertyId.replace(/-/g, " ").replace(/\d+/g, "").trim();
  const catName = prettyCategory(category);
  return `${catName} at ${propName} - Photo ${index + 1}`;
}

export function getPhotosForProperty(propertyId: string): PropertyPhotoEntry[] {
  const defs = P[propertyId];
  if (!defs) return [];

  // Filter duplicates (prefer .webp over .png/.jpg)
  const webpStems = new Set(
    defs.filter(d => d.f.endsWith(".webp")).map(d => d.f.replace(/\.webp$/, ""))
  );
  const filtered = defs.filter(d => {
    if (d.f.endsWith(".webp")) return true;
    const stem = d.f.replace(/\.(png|jpg|jpeg)$/, "");
    return !webpStems.has(stem);
  });

  // Sort by category order
  const sorted = [...filtered].sort((a, b) => {
    const ai = CATEGORY_ORDER.indexOf(a.c);
    const bi = CATEGORY_ORDER.indexOf(b.c);
    const aIdx = ai >= 0 ? ai : 999;
    const bIdx = bi >= 0 ? bi : 999;
    if (aIdx !== bIdx) return aIdx - bIdx;
    return a.f.localeCompare(b.f, undefined, { numeric: true });
  });

  // Convert to full entries with alt text
  const catCounters: Record<string, number> = {};
  return sorted.map(d => {
    catCounters[d.c] = (catCounters[d.c] || 0);
    const entry: PropertyPhotoEntry = {
      filename: d.f,
      category: d.c,
      url: d.u,
      alt: prettyAlt(propertyId, d.c, catCounters[d.c]),
    };
    catCounters[d.c]++;
    return entry;
  });
}

export const PROPERTY_PHOTOS = P;
