/**
 * Right at Home BnB - Static Property Data
 * Maps property directory slugs to VRBO listing data + photo manifest
 */

export interface PropertyListing {
  id: string;           // URL slug = directory name
  name: string;
  address: string;
  city: string;
  state: string;
  zipCode: string;
  bedrooms: number;
  bathrooms: number;
  sleeps: number;
  rating: number;       // out of 10
  reviewCount: number;
  vrboId?: string;
  vrboUrl?: string;
  amenities: string[];
  description: string;
  propertyType: 'HOUSE';
  nightlyRate: number;
  status: 'ACTIVE' | 'INACTIVE' | 'MAINTENANCE';
}

export interface PhotoManifest {
  [filename: string]: string; // filename -> category
}

// Category display names and sort order
export const CATEGORY_CONFIG: Record<string, { label: string; order: number }> = {
  'hero': { label: 'Featured', order: 0 },
  'exterior': { label: 'Exterior', order: 1 },
  'exterior-front': { label: 'Front Exterior', order: 1 },
  'exterior-back': { label: 'Back Exterior', order: 2 },
  'exterior-detail': { label: 'Exterior Detail', order: 3 },
  'living-room': { label: 'Living Room', order: 4 },
  'living-area': { label: 'Living Area', order: 4 },
  'interior': { label: 'Interior', order: 5 },
  'kitchen': { label: 'Kitchen', order: 6 },
  'private-kitchen': { label: 'Kitchen', order: 6 },
  'dining-room': { label: 'Dining Room', order: 7 },
  'dining': { label: 'Dining', order: 7 },
  'bedroom': { label: 'Bedroom', order: 8 },
  'master-bedroom': { label: 'Master Bedroom', order: 8 },
  'room': { label: 'Bedroom', order: 9 },
  'bathroom': { label: 'Bathroom', order: 10 },
  'master-bathroom': { label: 'Master Bathroom', order: 10 },
  'games-room': { label: 'Games Room', order: 11 },
  'pool': { label: 'Pool', order: 12 },
  'hot-tub': { label: 'Hot Tub', order: 13 },
  'patio': { label: 'Patio', order: 14 },
  'covered-patio': { label: 'Covered Patio', order: 14 },
  'terrace-patio': { label: 'Patio', order: 14 },
  'outdoor-dining': { label: 'Outdoor Dining', order: 15 },
  'yard': { label: 'Yard', order: 16 },
  'backyard': { label: 'Backyard', order: 16 },
  'property-grounds': { label: 'Property Grounds', order: 16 },
  'garage': { label: 'Garage', order: 17 },
  'laundry': { label: 'Laundry', order: 18 },
  'entrance': { label: 'Entrance', order: 19 },
  'hallway': { label: 'Hallway', order: 20 },
  'office': { label: 'Office', order: 21 },
  'childrens-area': { label: "Children's Area", order: 22 },
  'unknown': { label: 'Other', order: 99 },
};

// Normalize category names for the PropertyGallery component
export function normalizeCategory(cat: string): 'exterior' | 'living' | 'bedroom' | 'bathroom' | 'kitchen' | 'amenity' | 'other' {
  if (cat.includes('exterior') || cat === 'property-grounds') return 'exterior';
  if (cat.includes('living') || cat === 'interior' || cat.includes('hallway') || cat.includes('entrance')) return 'living';
  if (cat.includes('bed') || cat.includes('room') || cat === 'master-bedroom') return 'bedroom';
  if (cat.includes('bath') || cat === 'master-bathroom') return 'bathroom';
  if (cat.includes('kitchen') || cat.includes('dining')) return 'kitchen';
  if (['pool', 'hot-tub', 'patio', 'covered-patio', 'terrace-patio', 'games-room', 'yard', 'backyard', 'outdoor-dining', 'garage', 'laundry', 'office'].includes(cat)) return 'amenity';
  return 'other';
}

// All 21 properties
export const PROPERTIES: PropertyListing[] = [
  {
    id: 'castleford-5001',
    name: 'Adobe Compound with Pool and Fire Pits',
    address: '5001 Castleford',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 7,
    bathrooms: 2,
    sleeps: 16,
    rating: 8.8,
    reviewCount: 36,
    vrboId: '3005111',
    vrboUrl: 'https://www.vrbo.com/3005111',
    amenities: ['Pool', 'Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Free WiFi', 'Fire Pits', 'Billiards', 'Air Conditioning'],
    description: 'Massive adobe compound with private pool, fire pits, and billiards room. Perfect for large groups visiting the Permian Basin.',
    propertyType: 'HOUSE',
    nightlyRate: 350,
    status: 'ACTIVE',
  },
  {
    id: 'chelsea-3210',
    name: 'Chelsea Manor',
    address: '3210 Chelsea',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    rating: 9.2,
    reviewCount: 15,
    amenities: ['Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Free WiFi', 'Air Conditioning', 'Outdoor Dining', 'Private Kitchen'],
    description: 'Elegant Chelsea Manor with spacious rooms, private kitchen, and beautiful outdoor dining area.',
    propertyType: 'HOUSE',
    nightlyRate: 225,
    status: 'ACTIVE',
  },
  {
    id: 'Daventry-1309',
    name: 'Saddle Club',
    address: '1309 Daventry',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 8,
    rating: 10.0,
    reviewCount: 4,
    vrboId: '4750070',
    vrboUrl: 'https://www.vrbo.com/4750070',
    amenities: ['Washer', 'Dryer', 'Air Conditioning', 'Parking', 'Barbecue Grill', 'Children\'s Area', 'Large Yard'],
    description: 'Exceptional Saddle Club property with large yard, children\'s area, and covered parking. Perfect 10/10 rated.',
    propertyType: 'HOUSE',
    nightlyRate: 250,
    status: 'ACTIVE',
  },
  {
    id: 'Daventry-1311',
    name: 'Santiago Dreams',
    address: '1311 Daventry',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    rating: 10.0,
    reviewCount: 18,
    vrboId: '4179271',
    vrboUrl: 'https://www.vrbo.com/4179271',
    amenities: ['Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Free WiFi', 'Air Conditioning', 'Man Cave', 'Two Large Yards', 'Extra Parking'],
    description: 'Exceptional Santiago Dreams with man cave, two large yards, and perfect guest ratings. A true Texas hospitality experience.',
    propertyType: 'HOUSE',
    nightlyRate: 275,
    status: 'ACTIVE',
  },
  {
    id: 'Dentcrest-4707',
    name: 'Hot Tub Delight',
    address: '4707 Dentcrest',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 6,
    rating: 8.4,
    reviewCount: 28,
    vrboId: '2638481',
    vrboUrl: 'https://www.vrbo.com/2638481',
    amenities: ['Hot Tub', 'Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Free WiFi', 'Balcony', 'Outdoor Spa Tub'],
    description: 'Cozy Hot Tub Delight with outdoor spa, balcony, and all the comforts of home. Most reviewed property.',
    propertyType: 'HOUSE',
    nightlyRate: 175,
    status: 'ACTIVE',
  },
  {
    id: 'douglas-2800',
    name: 'Patio Home with Hot Tub',
    address: '2800 Douglas',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 8,
    rating: 8.6,
    reviewCount: 12,
    vrboId: '2634718',
    vrboUrl: 'https://www.vrbo.com/2634718',
    amenities: ['Hot Tub', 'Kitchen', 'Washer', 'Dryer', 'Multiple Outdoor Spaces', 'Air Conditioning', 'Parking'],
    description: 'Beautiful patio home with hot tub and multiple outdoor living spaces near Midland College.',
    propertyType: 'HOUSE',
    nightlyRate: 195,
    status: 'ACTIVE',
  },
  {
    id: 'garfield-2702',
    name: 'Oasis with Pool & Billiards',
    address: '2702 Garfield',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    rating: 9.0,
    reviewCount: 69,
    vrboId: '2636389',
    vrboUrl: 'https://www.vrbo.com/2636389',
    amenities: ['Private Pool', 'Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Free WiFi', 'Billiards'],
    description: 'Top-rated oasis with private pool and billiards. 69 reviews and counting. The ultimate Midland getaway.',
    propertyType: 'HOUSE',
    nightlyRate: 265,
    status: 'ACTIVE',
  },
  {
    id: 'Gleneagles-4735',
    name: 'Retreat with Covered Patio',
    address: '4735 Gleneagles',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 8,
    rating: 8.5,
    reviewCount: 10,
    vrboId: '2643784',
    vrboUrl: 'https://www.vrbo.com/2643784',
    amenities: ['Covered Patio', 'Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Free WiFi', 'Parking'],
    description: 'Comfortable retreat with a beautiful covered patio. Perfect for relaxing after a day in the Permian Basin.',
    propertyType: 'HOUSE',
    nightlyRate: 185,
    status: 'ACTIVE',
  },
  {
    id: 'Golf-Course-3209',
    name: 'Destination Getaway',
    address: '3209 Golf Course Rd',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 4,
    bathrooms: 2,
    sleeps: 10,
    rating: 8.8,
    reviewCount: 14,
    vrboId: '2643822',
    vrboUrl: 'https://www.vrbo.com/2643822',
    amenities: ['Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Free WiFi', 'Parking', 'Near Golf Course'],
    description: 'Prime destination getaway near the golf course. Spacious and well-appointed for groups.',
    propertyType: 'HOUSE',
    nightlyRate: 235,
    status: 'ACTIVE',
  },
  {
    id: 'haynes-2802',
    name: 'Old Midland Living',
    address: '2802 Haynes',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 16,
    rating: 8.5,
    reviewCount: 8,
    vrboId: '3355618',
    vrboUrl: 'https://www.vrbo.com/3355618',
    amenities: ['Pool', 'Hot Tub', 'Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Massive Yard'],
    description: 'Classic Old Midland living with pool, hot tub, and massive yard. Sleeps 16 for large groups.',
    propertyType: 'HOUSE',
    nightlyRate: 295,
    status: 'ACTIVE',
  },
  {
    id: 'Humble-3106',
    name: 'Outdoor Dream',
    address: '3106 Humble',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 4,
    bathrooms: 2,
    sleeps: 14,
    rating: 6.8,
    reviewCount: 5,
    vrboId: '4700881',
    vrboUrl: 'https://www.vrbo.com/4700881',
    amenities: ['Pool', 'Hot Tub', 'Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Patio', 'Outdoor Living Areas'],
    description: 'The Outdoor Dream with pool, hot tub, and expansive outdoor living areas. Perfect for families.',
    propertyType: 'HOUSE',
    nightlyRate: 245,
    status: 'ACTIVE',
  },
  {
    id: 'Lanham-1426',
    name: 'Posh & Private with Billiards',
    address: '1426 Lanham',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 3,
    bathrooms: 3,
    sleeps: 10,
    rating: 10.0,
    reviewCount: 6,
    vrboId: '4437486',
    vrboUrl: 'https://www.vrbo.com/4437486',
    amenities: ['Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Air Conditioning', 'Parking', 'Fireplace', 'Billiards Table'],
    description: 'Perfect 10/10 rated. Posh and private with a billiards table and fireplace. Intimate luxury.',
    propertyType: 'HOUSE',
    nightlyRate: 215,
    status: 'ACTIVE',
  },
  {
    id: 'lincoln-green-5055',
    name: 'Sprawling Ranch House with Pool Cabana',
    address: '5055 Lincoln Green',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 6,
    bathrooms: 3,
    sleeps: 18,
    rating: 9.0,
    reviewCount: 2,
    vrboId: '4581977',
    vrboUrl: 'https://www.vrbo.com/4581977',
    amenities: ['Pool', 'Washer', 'Dryer', 'Pet Friendly', 'Air Conditioning', 'Parking', 'Fireplace', 'Jetted Bathtub', 'Pool Cabana', 'Playground'],
    description: 'Massive sprawling ranch house with pool cabana and playground. Sleeps 18 — our largest property.',
    propertyType: 'HOUSE',
    nightlyRate: 395,
    status: 'ACTIVE',
  },
  {
    id: 'Mogford-1408',
    name: 'Clermont House with Pool & Billiards',
    address: '1408 Mogford',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 4,
    bathrooms: 2,
    sleeps: 10,
    rating: 9.0,
    reviewCount: 22,
    amenities: ['Pool', 'Billiards', 'Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Free WiFi'],
    description: 'The Clermont House with pool and billiards. Well-reviewed with 22 happy guests.',
    propertyType: 'HOUSE',
    nightlyRate: 255,
    status: 'ACTIVE',
  },
  {
    id: 'monterrey-1605',
    name: 'Monterrey House',
    address: '1605 Monterrey',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 6,
    rating: 8.4,
    reviewCount: 11,
    vrboId: '3477668',
    vrboUrl: 'https://www.vrbo.com/3477668',
    amenities: ['Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Free WiFi', 'Air Conditioning', 'Patio'],
    description: 'Charming Monterrey House with patio and all amenities. Great for small groups and couples.',
    propertyType: 'HOUSE',
    nightlyRate: 165,
    status: 'ACTIVE',
  },
  {
    id: 'Oriole-6100',
    name: 'Most Marvelous with Pool',
    address: '6100 Oriole',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 4,
    bathrooms: 2,
    sleeps: 8,
    rating: 9.6,
    reviewCount: 5,
    vrboId: '4471713',
    vrboUrl: 'https://www.vrbo.com/4471713',
    amenities: ['Pool', 'Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Air Conditioning', 'Fireplace'],
    description: 'Most Marvelous is right — exceptional 9.6 rating with private pool and fireplace.',
    propertyType: 'HOUSE',
    nightlyRate: 235,
    status: 'ACTIVE',
  },
  {
    id: 'shandon-3528',
    name: 'Uptown Place with Gated Yard',
    address: '3528 Shandon',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 8,
    rating: 8.8,
    reviewCount: 17,
    amenities: ['Gated Yard', 'Covered Parking', 'Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Free WiFi'],
    description: 'Uptown Place with gated yard and covered parking. Secure and comfortable.',
    propertyType: 'HOUSE',
    nightlyRate: 195,
    status: 'ACTIVE',
  },
  {
    id: 'Siesta-4217',
    name: 'Cowboy Siesta Corner Lot',
    address: '4217 Siesta',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 6,
    rating: 9.0,
    reviewCount: 3,
    amenities: ['Patio', 'Covered Parking', 'Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Corner Lot'],
    description: 'New listing! Cowboy Siesta on a corner lot with patio and covered parking.',
    propertyType: 'HOUSE',
    nightlyRate: 175,
    status: 'ACTIVE',
  },
  {
    id: 'storey-4801',
    name: 'Safari Game Room',
    address: '4801 Storey',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 8,
    rating: 8.5,
    reviewCount: 10,
    vrboId: '2638524',
    vrboUrl: 'https://www.vrbo.com/2638524',
    amenities: ['Game Room', 'Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Free WiFi', 'Safari Theme'],
    description: 'Unique safari-themed game room makes this a one-of-a-kind Midland stay.',
    propertyType: 'HOUSE',
    nightlyRate: 195,
    status: 'ACTIVE',
  },
  {
    id: 'Vanguard-1633',
    name: 'Vanguard Velvet Lounge',
    address: '1633 Vanguard',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 8,
    rating: 8.8,
    reviewCount: 17,
    amenities: ['Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Free WiFi', 'Stylish Decor'],
    description: 'The Vanguard Velvet Lounge with stylish decor and 17 positive reviews.',
    propertyType: 'HOUSE',
    nightlyRate: 185,
    status: 'ACTIVE',
  },
  {
    id: 'Vanguard-6613',
    name: 'Groovy Times with Pool',
    address: '6613 Vanguard',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 8,
    rating: 8.5,
    reviewCount: 8,
    amenities: ['Pool', 'Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Free WiFi', 'Retro Theme'],
    description: 'Groovy Times with pool and retro vibes. Fun themed property for a memorable stay.',
    propertyType: 'HOUSE',
    nightlyRate: 215,
    status: 'ACTIVE',
  },
];

export function getPropertyById(id: string): PropertyListing | undefined {
  return PROPERTIES.find(p => p.id === id);
}

export function getPropertySlugs(): string[] {
  return PROPERTIES.map(p => p.id);
}
