/**
 * Right at Home BnB - Static Property Data
 * Maps property directory slugs to VRBO listing data + photo manifest
 */

export interface RoomInfo {
  name: string;
  beds: string;
}

export interface BathroomInfo {
  name: string;
  features: string;
}

export interface PropertyListing {
  id: string;           // URL slug = directory name
  name: string;
  address: string;
  city: string;
  state: string;
  zipCode: string;
  bedrooms: number;
  bathrooms: number;
  sleeps: number;
  rating: number;       // out of 10
  reviewCount: number;
  vrboId?: string;
  vrboUrl?: string;
  amenities: string[];
  description: string;
  fullDescription: string;
  rooms: RoomInfo[];
  bathrooms_detail: BathroomInfo[];
  spaces: string[];
  highlights: string[];
  petPolicy: string;
  checkInTime: string;
  checkOutTime: string;
  cleaningFee?: number;
  propertyType: 'HOUSE';
  nightlyRate: number;
  status: 'ACTIVE' | 'INACTIVE' | 'MAINTENANCE';
}

export interface PhotoManifest {
  [filename: string]: string; // filename -> category
}

// Category display names and sort order
export const CATEGORY_CONFIG: Record<string, { label: string; order: number }> = {
  'hero': { label: 'Featured', order: 0 },
  'exterior': { label: 'Exterior', order: 1 },
  'exterior-front': { label: 'Front Exterior', order: 1 },
  'exterior-back': { label: 'Back Exterior', order: 2 },
  'exterior-detail': { label: 'Exterior Detail', order: 3 },
  'living-room': { label: 'Living Room', order: 4 },
  'living-area': { label: 'Living Area', order: 4 },
  'interior': { label: 'Interior', order: 5 },
  'kitchen': { label: 'Kitchen', order: 6 },
  'private-kitchen': { label: 'Kitchen', order: 6 },
  'dining-room': { label: 'Dining Room', order: 7 },
  'dining': { label: 'Dining', order: 7 },
  'bedroom': { label: 'Bedroom', order: 8 },
  'master-bedroom': { label: 'Master Bedroom', order: 8 },
  'room': { label: 'Bedroom', order: 9 },
  'bathroom': { label: 'Bathroom', order: 10 },
  'master-bathroom': { label: 'Master Bathroom', order: 10 },
  'games-room': { label: 'Games Room', order: 11 },
  'pool': { label: 'Pool', order: 12 },
  'hot-tub': { label: 'Hot Tub', order: 13 },
  'patio': { label: 'Patio', order: 14 },
  'covered-patio': { label: 'Covered Patio', order: 14 },
  'terrace-patio': { label: 'Patio', order: 14 },
  'outdoor-dining': { label: 'Outdoor Dining', order: 15 },
  'yard': { label: 'Yard', order: 16 },
  'backyard': { label: 'Backyard', order: 16 },
  'property-grounds': { label: 'Property Grounds', order: 16 },
  'garage': { label: 'Garage', order: 17 },
  'laundry': { label: 'Laundry', order: 18 },
  'entrance': { label: 'Entrance', order: 19 },
  'hallway': { label: 'Hallway', order: 20 },
  'office': { label: 'Office', order: 21 },
  'childrens-area': { label: "Children's Area", order: 22 },
  'unknown': { label: 'Other', order: 99 },
};

// Normalize category names for the PropertyGallery component
export function normalizeCategory(cat: string): 'exterior' | 'living' | 'bedroom' | 'bathroom' | 'kitchen' | 'amenity' | 'other' {
  if (cat.includes('exterior') || cat === 'property-grounds') return 'exterior';
  if (cat.includes('living') || cat === 'interior' || cat.includes('hallway') || cat.includes('entrance')) return 'living';
  if (cat.includes('bed') || cat.includes('room') || cat === 'master-bedroom') return 'bedroom';
  if (cat.includes('bath') || cat === 'master-bathroom') return 'bathroom';
  if (cat.includes('kitchen') || cat.includes('dining')) return 'kitchen';
  if (['pool', 'hot-tub', 'patio', 'covered-patio', 'terrace-patio', 'games-room', 'yard', 'backyard', 'outdoor-dining', 'garage', 'laundry', 'office'].includes(cat)) return 'amenity';
  return 'other';
}

// ══════════════════════════════════════════════════════════════
// CORRECTED from VRBO Partner Central dashboard — April 2026
// 31 total VRBO properties: 18 Active, 13 Inactive
// ══════════════════════════════════════════════════════════════

// ── ACTIVE PROPERTIES (18) ──────────────────────────────────
export const PROPERTIES: PropertyListing[] = [
  {
    id: 'castleford-5001',
    name: 'Oasis with Pool & Billiards',
    address: '5005 Castleford Rd',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    rating: 9.0,
    reviewCount: 71,
    vrboId: '2636389',
    vrboUrl: 'https://www.vrbo.com/2636389',
    amenities: ['Private Pool', 'Billiards', 'Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Free WiFi', 'Air Conditioning'],
    description: 'Top-rated oasis with private pool and billiards. 71 reviews — the most reviewed Right at Home property.',
    fullDescription: 'Welcome to our top-rated oasis — the most reviewed property in the Right at Home portfolio with 71 glowing reviews. Take a dip in the private pool, challenge your crew to a game of billiards, or relax in the spacious living areas. The fully equipped kitchen makes cooking for your group a breeze, and every room has WiFi and smart TV access. Pet friendly, so bring the whole family. Our prices include all fees — no hidden surprises.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '1 Queen Bed' },
      { name: 'Bedroom 4', beds: '2 Twin Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
      { name: 'Bathroom 3', features: 'Shower only · Toilet' },
    ],
    spaces: ['Porch', 'Kitchen', 'Dining area', 'Pool deck', 'Game room'],
    highlights: ['Entire house', '4 bed, 3 bath', 'Sleeps 10', 'Private Pool', 'Billiards', 'Pet Friendly'],
    petPolicy: 'Pet friendly - bring your furry friends',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 265,
    status: 'ACTIVE',
  },
  {
    id: 'Golf-Course-3209',
    name: 'Adobe Compound with Pool and Fire Pits and Billiards',
    address: '2309 W Golf Course Rd',
    city: 'Midland',
    state: 'TX',
    zipCode: '79701',
    bedrooms: 7,
    bathrooms: 2,
    sleeps: 19,
    rating: 8.8,
    reviewCount: 38,
    vrboId: '3005111',
    vrboUrl: 'https://www.vrbo.com/3005111',
    amenities: ['Pool', 'Fire Pits', 'Billiards', 'Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Free WiFi', 'Air Conditioning'],
    description: 'Massive adobe compound with private pool, fire pits, and billiards room. Sleeps 19 for large groups.',
    fullDescription: 'Private retreat in the heart of Midland. Enjoy this entire home with complete privacy and plenty of parking for your family or coworkers. Should you only need the main house, ask for a discount. All rooms have televisions with WiFi and smart apps. Fully equipped kitchen and indoor dining for 14. The casita out back features 4 bedrooms with a half bath and kitchenette. Outdoor dining and grilling available with plenty of seating and putting green near the two fire pits. There is also a bonus man cave in the back of the home that features a pool table with two large tables for seating, and a spare refrigerator. Our prices include all fees. No hidden fees.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 Queen Bed and 1 Twin Bed' },
      { name: 'Bedroom 2', beds: '1 Double Bed' },
      { name: 'Bedroom 3', beds: '1 Queen Bed' },
      { name: 'Bedroom 4', beds: '1 Queen Bed' },
      { name: 'Bedroom 5', beds: '1 Queen Bed' },
      { name: 'Bedroom 6', beds: '1 Queen Bed' },
      { name: 'Bedroom 7', beds: '2 Queen Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Toilet · Shower only' },
      { name: 'Bathroom 2', features: 'Bathtub or shower · Toilet' },
      { name: 'Half Bath', features: 'Toilet' },
    ],
    spaces: ['Porch/Lanai', 'Kitchen', 'Separate dining area', 'Outdoor play area', 'Dining area'],
    highlights: ['Entire house', '7 bed, 2 bath', 'Sleeps 19', 'Perfect for groups', 'Midland, TX', 'Permian Basin', 'Pet Friendly'],
    petPolicy: 'Pet friendly - bring your furry friends',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 350,
    status: 'ACTIVE',
  },
  {
    id: 'garfield-2702',
    name: 'Patio Home with Hot Tub',
    address: '2702 N Garfield St',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 3,
    bathrooms: 4,
    sleeps: 6,
    rating: 8.4,
    reviewCount: 29,
    vrboId: '2634718',
    vrboUrl: 'https://www.vrbo.com/2634718',
    amenities: ['Hot Tub', 'Kitchen', 'Washer', 'Dryer', 'Multiple Outdoor Spaces', 'Air Conditioning', 'Parking'],
    description: 'Beautiful patio home with hot tub and multiple outdoor living spaces.',
    fullDescription: 'Unwind in this beautiful patio home featuring a private hot tub and multiple outdoor living spaces perfect for relaxing after a long day. The fully equipped kitchen and comfortable bedrooms make this your home away from home in Midland. With 4 full bathrooms for just 3 bedrooms, you will never have to wait in line. Enjoy the covered patio, open-air seating areas, and peaceful neighborhood setting.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '2 Twin Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
      { name: 'Bathroom 3', features: 'Shower only · Toilet' },
      { name: 'Bathroom 4', features: 'Shower only · Toilet' },
    ],
    spaces: ['Covered patio', 'Kitchen', 'Outdoor seating area', 'Hot tub deck', 'Dining area'],
    highlights: ['Entire house', '3 bed, 4 bath', 'Sleeps 6', 'Hot Tub', 'Multiple patios'],
    petPolicy: 'No pets allowed',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 200,
    status: 'ACTIVE',
  },
  {
    id: 'douglas-2000',
    name: 'Old Midland Living',
    address: '2000 Douglas Ave',
    city: 'Midland',
    state: 'TX',
    zipCode: '79701',
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 16,
    rating: 8.5,
    reviewCount: 24,
    vrboId: '3355618',
    vrboUrl: 'https://www.vrbo.com/3355618',
    amenities: ['Pool', 'Hot Tub', 'Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Massive Yard'],
    description: 'Classic Old Midland living with massive yard. Sleeps 16 for large groups.',
    fullDescription: 'Experience classic Old Midland living in this spacious home with a massive yard, private pool, and hot tub. With room to sleep 16, this is the perfect gathering spot for large families, work crews, or friend groups visiting the Permian Basin. The fully equipped kitchen can handle cooking for a crowd, and the sprawling yard gives everyone room to spread out. Pet friendly, so the whole family is welcome.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '2 Queen Beds' },
      { name: 'Bedroom 3', beds: '1 Queen Bed and 1 Twin Bed' },
      { name: 'Bedroom 4', beds: '2 Double Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
      { name: 'Bathroom 3', features: 'Shower only · Toilet' },
    ],
    spaces: ['Massive yard', 'Pool deck', 'Hot tub area', 'Kitchen', 'Dining area', 'Porch'],
    highlights: ['Entire house', '4 bed, 3 bath', 'Sleeps 16', 'Pool & Hot Tub', 'Massive yard', 'Pet Friendly'],
    petPolicy: 'Pet friendly - bring your furry friends',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 295,
    status: 'ACTIVE',
  },
  {
    id: 'Dentcrest-4707',
    name: 'Hot Tub Delight',
    address: '4707 Dentcrest Dr',
    city: 'Midland',
    state: 'TX',
    zipCode: '79707',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 6,
    rating: 8.4,
    reviewCount: 31,
    vrboId: '2638481',
    vrboUrl: 'https://www.vrbo.com/2638481',
    amenities: ['Hot Tub', 'Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Free WiFi', 'Balcony', 'Outdoor Spa Tub'],
    description: 'Cozy Hot Tub Delight in Wydewood Estates with outdoor spa and all the comforts of home.',
    fullDescription: 'Sink into the hot tub after a long day and let your worries melt away at this cozy Wydewood Estates retreat. The outdoor spa tub and balcony give you multiple ways to enjoy the Texas evenings. Inside you will find a fully equipped kitchen, comfortable bedrooms, and all the comforts of home including WiFi and smart TVs. Pet friendly and perfectly sized for couples or small groups.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '2 Twin Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
    ],
    spaces: ['Balcony', 'Kitchen', 'Hot tub area', 'Dining area', 'Patio'],
    highlights: ['Entire house', '3 bed, 2 bath', 'Sleeps 6', 'Hot Tub', 'Balcony', 'Pet Friendly'],
    petPolicy: 'Pet friendly - bring your furry friends',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 175,
    status: 'ACTIVE',
  },
  {
    id: 'chelsea-3210',
    name: 'Retreat with Covered Patio',
    address: '3210 Chelsea Pl',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 4,
    bathrooms: 2,
    sleeps: 8,
    rating: 9.2,
    reviewCount: 33,
    vrboId: '2643784',
    vrboUrl: 'https://www.vrbo.com/2643784',
    amenities: ['Covered Patio', 'Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Free WiFi', 'Parking'],
    description: 'Comfortable retreat with a beautiful covered patio. 33 happy guest reviews.',
    fullDescription: 'This highly rated retreat features a beautiful covered patio perfect for morning coffee or evening relaxation. With 33 happy guest reviews and a 9.2 rating, guests consistently love their stay here. The home offers 4 comfortable bedrooms, a fully equipped kitchen, and all the essentials including WiFi, washer and dryer, and plenty of parking. A wonderful base for exploring Midland.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '1 Queen Bed' },
      { name: 'Bedroom 4', beds: '2 Twin Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
    ],
    spaces: ['Covered patio', 'Kitchen', 'Living room', 'Dining area', 'Parking area'],
    highlights: ['Entire house', '4 bed, 2 bath', 'Sleeps 8', '9.2 Rating', 'Covered Patio', '33 Reviews'],
    petPolicy: 'No pets allowed',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 225,
    status: 'ACTIVE',
  },
  {
    id: 'storey-4801',
    name: 'Destination Getaway',
    address: '4801 Storey Ave',
    city: 'Midland',
    state: 'TX',
    zipCode: '79703',
    bedrooms: 4,
    bathrooms: 2,
    sleeps: 10,
    rating: 8.8,
    reviewCount: 24,
    vrboId: '2643822',
    vrboUrl: 'https://www.vrbo.com/2643822',
    amenities: ['Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Free WiFi', 'Parking'],
    description: 'Spacious destination getaway on Storey Ave. Well-appointed for groups.',
    fullDescription: 'Make this spacious Storey Avenue home your destination getaway in Midland. Well-appointed for groups of up to 10, this 4-bedroom home offers everything you need for a comfortable stay. The fully equipped kitchen and generous living spaces make it easy to settle in, while WiFi and in-unit laundry keep you connected and comfortable. Plenty of parking for the whole crew.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '1 Queen Bed' },
      { name: 'Bedroom 4', beds: '1 Queen Bed and 1 Twin Bed' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
    ],
    spaces: ['Kitchen', 'Living room', 'Dining area', 'Porch', 'Parking area'],
    highlights: ['Entire house', '4 bed, 2 bath', 'Sleeps 10', 'Great for groups', 'Midland, TX'],
    petPolicy: 'No pets allowed',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 235,
    status: 'ACTIVE',
  },
  {
    id: 'Daventry-1309',
    name: 'Saddle Club',
    address: '1309 Daventry Pl',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 8,
    rating: 10.0,
    reviewCount: 8,
    vrboId: '4750070',
    vrboUrl: 'https://www.vrbo.com/4750070',
    amenities: ['Washer', 'Dryer', 'Air Conditioning', 'Parking', 'Barbecue Grill', 'Children\'s Area', 'Large Yard'],
    description: 'Exceptional Saddle Club property with large yard and children\'s area. Perfect 10/10 rated.',
    fullDescription: 'Welcome to the Saddle Club — our perfect 10/10 rated property that guests absolutely love. This family-friendly home features a large yard with a dedicated children\'s area, making it ideal for families with kids. Fire up the barbecue grill for a Texas cookout in the spacious backyard. Four comfortable bedrooms and three full bathrooms ensure everyone has their own space. Every guest has given this home a perfect score — come see why.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '1 Queen Bed' },
      { name: 'Bedroom 4', beds: '2 Twin Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
      { name: 'Bathroom 3', features: 'Shower only · Toilet' },
    ],
    spaces: ['Large yard', 'Children\'s area', 'BBQ area', 'Kitchen', 'Dining area', 'Porch'],
    highlights: ['Entire house', '4 bed, 3 bath', 'Sleeps 8', 'Perfect 10/10', 'Family Friendly', 'BBQ Grill'],
    petPolicy: 'No pets allowed',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 250,
    status: 'ACTIVE',
  },
  {
    id: 'Daventry-1311',
    name: 'Santiago Dreams',
    address: '1311 Daventry Pl',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    rating: 10.0,
    reviewCount: 20,
    vrboId: '4179271',
    vrboUrl: 'https://www.vrbo.com/4179271',
    amenities: ['Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Free WiFi', 'Air Conditioning', 'Man Cave', 'Two Large Yards', 'Extra Parking'],
    description: 'Santiago Dreams with man cave, two large yards, and perfect guest ratings.',
    fullDescription: 'Another perfect 10/10 from 20 guests — Santiago Dreams delivers every time. This home features a dedicated man cave for hanging out, two large yards for outdoor fun, and extra parking for work crews or large groups. The fully equipped kitchen, WiFi throughout, and in-unit laundry make this a true home away from home. Pet friendly so your four-legged family members are welcome too.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '1 Queen Bed' },
      { name: 'Bedroom 4', beds: '2 Queen Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
      { name: 'Bathroom 3', features: 'Shower only · Toilet' },
    ],
    spaces: ['Man cave', 'Two large yards', 'Kitchen', 'Dining area', 'Extra parking', 'Porch'],
    highlights: ['Entire house', '4 bed, 3 bath', 'Sleeps 10', 'Perfect 10/10', 'Man Cave', 'Pet Friendly'],
    petPolicy: 'Pet friendly - bring your furry friends',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 275,
    status: 'ACTIVE',
  },
  {
    id: 'lincoln-green-5055',
    name: 'Sprawling Ranch House with Pool Cabana and Playground',
    address: '5800 Lincoln Green Ct',
    city: 'Midland',
    state: 'TX',
    zipCode: '79707',
    bedrooms: 6,
    bathrooms: 3,
    sleeps: 18,
    rating: 9.0,
    reviewCount: 3,
    vrboId: '4581977',
    vrboUrl: 'https://www.vrbo.com/4581977',
    amenities: ['Pool', 'Washer', 'Dryer', 'Pet Friendly', 'Air Conditioning', 'Parking', 'Fireplace', 'Pool Cabana', 'Playground'],
    description: 'Massive sprawling ranch house with pool cabana and playground. Sleeps 18 — our largest property.',
    fullDescription: 'Our largest property — a sprawling ranch house that sleeps 18 with room to spare. The pool cabana provides a shaded retreat by the water, while the kids burn off energy on the playground. Inside you will find a cozy fireplace, spacious living areas, and a fully equipped kitchen ready for large group meals. Six bedrooms, three bathrooms, and plenty of parking make this the ultimate group destination in Midland. Pet friendly.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 King Bed' },
      { name: 'Bedroom 3', beds: '1 Queen Bed' },
      { name: 'Bedroom 4', beds: '1 Queen Bed' },
      { name: 'Bedroom 5', beds: '2 Queen Beds' },
      { name: 'Bedroom 6', beds: '2 Twin Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
      { name: 'Bathroom 3', features: 'Shower only · Toilet' },
    ],
    spaces: ['Pool cabana', 'Playground', 'Pool deck', 'Kitchen', 'Dining area', 'Living room with fireplace', 'Porch'],
    highlights: ['Entire house', '6 bed, 3 bath', 'Sleeps 18', 'Pool & Cabana', 'Playground', 'Pet Friendly'],
    petPolicy: 'Pet friendly - bring your furry friends',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 395,
    status: 'ACTIVE',
  },
  {
    id: 'shandon-3528',
    name: 'Groovy Times with Pool',
    address: '3528 W Shandon Ave',
    city: 'Midland',
    state: 'TX',
    zipCode: '79707',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 8,
    rating: 8.5,
    reviewCount: 2,
    vrboId: '4894280',
    vrboUrl: 'https://www.vrbo.com/4894280',
    amenities: ['Pool', 'Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Free WiFi'],
    description: 'Groovy Times with pool. Fun themed property for a memorable Midland stay.',
    fullDescription: 'Get ready for Groovy Times at this fun-themed Midland home with a private pool. The retro vibes and unique decor make every photo Instagram-worthy and every stay memorable. Cool off in the pool, cook in the fully equipped kitchen, and enjoy WiFi and AC throughout. Perfect for families or friend groups looking for something a little different from the ordinary.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '2 Twin Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
    ],
    spaces: ['Pool deck', 'Kitchen', 'Living room', 'Dining area', 'Patio'],
    highlights: ['Entire house', '3 bed, 2 bath', 'Sleeps 8', 'Private Pool', 'Fun Theme'],
    petPolicy: 'No pets allowed',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 215,
    status: 'ACTIVE',
  },
  {
    id: 'monterrey-1605',
    name: 'Monterrey House',
    address: '1605 Monterrey Dr',
    city: 'Midland',
    state: 'TX',
    zipCode: '79703',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 6,
    rating: 8.4,
    reviewCount: 11,
    vrboId: '3477668',
    vrboUrl: 'https://www.vrbo.com/3477668',
    amenities: ['Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Free WiFi', 'Air Conditioning', 'Patio'],
    description: 'Charming Monterrey House with patio and all amenities. Great for small groups.',
    fullDescription: 'The charming Monterrey House offers a warm, welcoming stay with a lovely patio for outdoor relaxation. This well-maintained 3-bedroom home is perfect for small groups, couples, or business travelers visiting the Permian Basin. Enjoy the fully equipped kitchen, free WiFi, in-unit laundry, and comfortable living spaces. Pet friendly, so your furry companions are welcome to join the trip.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 Queen Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '2 Twin Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
    ],
    spaces: ['Patio', 'Kitchen', 'Living room', 'Dining area'],
    highlights: ['Entire house', '3 bed, 2 bath', 'Sleeps 6', 'Great value', 'Pet Friendly'],
    petPolicy: 'Pet friendly - bring your furry friends',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 165,
    status: 'ACTIVE',
  },
  {
    id: 'Gleneagles-4735',
    name: 'Northtown Place',
    address: '4535 Gleneagles Dr',
    city: 'Midland',
    state: 'TX',
    zipCode: '79707',
    bedrooms: 2,
    bathrooms: 2,
    sleeps: 4,
    rating: 9.0,
    reviewCount: 30,
    vrboId: '2643808',
    vrboUrl: 'https://www.vrbo.com/2643808',
    amenities: ['Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Free WiFi', 'Parking'],
    description: 'Northtown Place — 30 reviews and counting. Compact and comfortable.',
    fullDescription: 'Northtown Place is one of our most consistently loved properties with 30 reviews and a 9.0 rating. This compact and comfortable 2-bedroom home is ideal for couples, solo travelers, or small business trips. Everything you need is here — a full kitchen, WiFi, washer and dryer, AC, and dedicated parking. No wasted space, no wasted money, just a clean and comfortable Midland stay.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 Queen Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
    ],
    spaces: ['Kitchen', 'Living room', 'Dining area', 'Parking area'],
    highlights: ['Entire house', '2 bed, 2 bath', 'Sleeps 4', '30 Reviews', '9.0 Rating'],
    petPolicy: 'No pets allowed',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 185,
    status: 'ACTIVE',
  },
  {
    id: 'Humble-3106',
    name: 'Outdoor Dream',
    address: '3104 Humble Ave',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 4,
    bathrooms: 2,
    sleeps: 14,
    rating: 6.8,
    reviewCount: 5,
    vrboId: '4700881',
    vrboUrl: 'https://www.vrbo.com/4700881',
    amenities: ['Pool', 'Hot Tub', 'Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Patio', 'Outdoor Living Areas'],
    description: 'The Outdoor Dream with pool, hot tub, and expansive outdoor living areas.',
    fullDescription: 'Live the Outdoor Dream at this expansive Midland property featuring a private pool, hot tub, and multiple outdoor living areas. Whether you are lounging poolside, soaking in the hot tub under the stars, or grilling on the patio, this home is built for outdoor living. Inside, 4 bedrooms sleep up to 14, and the full kitchen handles group meals with ease. Pet friendly and perfect for large gatherings.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '2 Queen Beds' },
      { name: 'Bedroom 3', beds: '1 Queen Bed' },
      { name: 'Bedroom 4', beds: '2 Double Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
    ],
    spaces: ['Pool deck', 'Hot tub area', 'Patio', 'Outdoor living areas', 'Kitchen', 'Dining area'],
    highlights: ['Entire house', '4 bed, 2 bath', 'Sleeps 14', 'Pool & Hot Tub', 'Outdoor Living', 'Pet Friendly'],
    petPolicy: 'Pet friendly - bring your furry friends',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 245,
    status: 'ACTIVE',
  },
  {
    id: 'posh-private-1426',
    name: 'Posh & Private with Billiards',
    address: '1426 Lanham St',
    city: 'Midland',
    state: 'TX',
    zipCode: '79701',
    bedrooms: 3,
    bathrooms: 3,
    sleeps: 10,
    rating: 10.0,
    reviewCount: 9,
    vrboId: '4437486',
    vrboUrl: 'https://www.vrbo.com/4437486',
    amenities: ['Billiards Table', 'Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Air Conditioning', 'Parking', 'Fireplace'],
    description: 'Perfect 10/10 rated. Posh and private with billiards table and fireplace.',
    fullDescription: 'Posh, private, and perfect — this 10/10 rated home delivers an upscale Midland experience. Challenge your group to billiards, warm up by the fireplace, or simply enjoy the well-appointed living spaces. Three bedrooms and three full bathrooms give everyone room to breathe, while the full kitchen and in-unit laundry keep everything convenient. Pet friendly and with ample parking for the whole crew.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '2 Queen Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
      { name: 'Bathroom 3', features: 'Shower only · Toilet' },
    ],
    spaces: ['Game room with billiards', 'Kitchen', 'Living room with fireplace', 'Dining area', 'Parking area'],
    highlights: ['Entire house', '3 bed, 3 bath', 'Sleeps 10', 'Perfect 10/10', 'Billiards', 'Pet Friendly'],
    petPolicy: 'Pet friendly - bring your furry friends',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 215,
    status: 'ACTIVE',
  },
  {
    id: 'Siesta-4217',
    name: 'Cowboy Siesta Corner Lot',
    address: '4217 Siesta Ln',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 6,
    rating: 9.0,
    reviewCount: 7,
    vrboId: '4135262',
    vrboUrl: 'https://www.vrbo.com/4135262',
    amenities: ['Patio', 'Covered Parking', 'Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Corner Lot'],
    description: 'Cowboy Siesta on a corner lot with patio and covered parking.',
    fullDescription: 'Kick back at the Cowboy Siesta — a charming corner lot home with a great patio and covered parking. This 3-bedroom retreat is perfect for couples or small groups who want a comfortable, no-fuss Midland stay. The fully equipped kitchen, washer and dryer, and AC throughout keep everything easy. The corner lot gives you extra privacy and a spacious feel that sets this property apart.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '2 Twin Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
    ],
    spaces: ['Patio', 'Kitchen', 'Living room', 'Dining area', 'Covered parking'],
    highlights: ['Entire house', '3 bed, 2 bath', 'Sleeps 6', 'Corner Lot', 'Covered Parking', '9.0 Rating'],
    petPolicy: 'No pets allowed',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 175,
    status: 'ACTIVE',
  },
  {
    id: 'Mogford-1408',
    name: 'Clermont House with Pool & Billiards',
    address: '1408 Mogford St',
    city: 'Midland',
    state: 'TX',
    zipCode: '79701',
    bedrooms: 5,
    bathrooms: 2,
    sleeps: 14,
    rating: 9.0,
    reviewCount: 25,
    vrboId: '3724481',
    vrboUrl: 'https://www.vrbo.com/3724481',
    amenities: ['Pool', 'Billiards', 'Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Free WiFi'],
    description: 'The Clermont House with pool and billiards. 25 happy guest reviews.',
    fullDescription: 'The Clermont House brings together a private pool and billiards room for the ultimate group getaway. With 25 happy guest reviews and a 9.0 rating, this 5-bedroom home consistently delivers. The spacious layout sleeps 14, making it perfect for work crews, family reunions, or friend trips. Fully equipped kitchen, WiFi, laundry, and AC throughout. Dive in the pool by day, shoot billiards by night.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '1 Queen Bed' },
      { name: 'Bedroom 4', beds: '2 Double Beds' },
      { name: 'Bedroom 5', beds: '2 Twin Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
    ],
    spaces: ['Pool deck', 'Game room with billiards', 'Kitchen', 'Living room', 'Dining area', 'Patio'],
    highlights: ['Entire house', '5 bed, 2 bath', 'Sleeps 14', 'Private Pool', 'Billiards', '25 Reviews'],
    petPolicy: 'No pets allowed',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 346,
    status: 'ACTIVE',
  },
  {
    id: 'blazing-saddle-2501',
    name: 'Mockingbird Ridge',
    address: '2501 Blazing Saddle Blvd',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 6,
    rating: 8.0,
    reviewCount: 1,
    vrboId: '5103283',
    vrboUrl: 'https://www.vrbo.com/5103283',
    amenities: ['Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Parking'],
    description: 'Mockingbird Ridge on Blazing Saddle Blvd. Newest Right at Home property.',
    fullDescription: 'Welcome to Mockingbird Ridge — the newest addition to the Right at Home portfolio. This fresh, clean 3-bedroom home on Blazing Saddle Blvd offers a comfortable stay with all the essentials. The fully equipped kitchen, washer and dryer, AC, and dedicated parking make your Midland visit hassle-free. Be among the first guests to experience this property and help us build its reputation.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '2 Twin Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
    ],
    spaces: ['Kitchen', 'Living room', 'Dining area', 'Parking area', 'Porch'],
    highlights: ['Entire house', '3 bed, 2 bath', 'Sleeps 6', 'Newest Property', 'Midland, TX'],
    petPolicy: 'No pets allowed',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 195,
    status: 'ACTIVE',
  },

  // ── INACTIVE PROPERTIES (on VRBO but currently not taking bookings) ───
  {
    id: 'haynes-2802',
    name: 'Safari Gameroom',
    address: '2802 Haynes Dr',
    city: 'Midland',
    state: 'TX',
    zipCode: '79705',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 8,
    rating: 8.5,
    reviewCount: 48,
    vrboId: '2638524',
    vrboUrl: 'https://www.vrbo.com/2638524',
    amenities: ['Game Room', 'Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Free WiFi', 'Safari Theme'],
    description: 'Safari-themed game room. 48 reviews. Currently inactive on VRBO.',
    fullDescription: 'The Safari Gameroom brings wild fun to Midland with its safari-themed decor and dedicated game room. With 48 reviews this is one of our most popular properties. Currently inactive on VRBO — check back soon.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '2 Twin Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
    ],
    spaces: ['Game room', 'Kitchen', 'Living room', 'Dining area'],
    highlights: ['Entire house', '3 bed, 2 bath', 'Sleeps 8', 'Game Room', '48 Reviews'],
    petPolicy: 'No pets allowed',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 195,
    status: 'INACTIVE',
  },
  {
    id: 'Vanguard-6613',
    name: 'Vanguard Velvet Lounge',
    address: '6613 Vanguard Rd',
    city: 'Midland',
    state: 'TX',
    zipCode: '79706',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 8,
    rating: 8.8,
    reviewCount: 21,
    vrboId: '3559249',
    vrboUrl: 'https://www.vrbo.com/3559249',
    amenities: ['Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Free WiFi', 'Stylish Decor'],
    description: 'Vanguard Velvet Lounge with stylish decor. Currently inactive on VRBO.',
    fullDescription: 'The Vanguard Velvet Lounge features stylish, eye-catching decor that makes every stay feel special. With 21 reviews and an 8.8 rating, guests love the vibe. Currently inactive on VRBO — check back soon.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '2 Twin Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
    ],
    spaces: ['Kitchen', 'Living room', 'Dining area'],
    highlights: ['Entire house', '3 bed, 2 bath', 'Sleeps 8', 'Stylish Decor'],
    petPolicy: 'No pets allowed',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 185,
    status: 'INACTIVE',
  },
  {
    id: 'Oriole-6100',
    name: 'Most Marvelous with Pool',
    address: '6100 Oriole Dr',
    city: 'Midland',
    state: 'TX',
    zipCode: '79707',
    bedrooms: 4,
    bathrooms: 2,
    sleeps: 8,
    rating: 9.6,
    reviewCount: 5,
    vrboId: '4471713',
    vrboUrl: 'https://www.vrbo.com/4471713',
    amenities: ['Pool', 'Kitchen', 'Washer', 'Dryer', 'Pet Friendly', 'Air Conditioning', 'Fireplace'],
    description: 'Most Marvelous — exceptional 9.6 rating with private pool. Currently inactive on VRBO.',
    fullDescription: 'Truly the Most Marvelous — this exceptional 9.6-rated property features a private pool and cozy fireplace. Pet friendly with a full kitchen and all the comforts. Currently inactive on VRBO — check back soon.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '1 Queen Bed' },
      { name: 'Bedroom 4', beds: '2 Twin Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
    ],
    spaces: ['Pool deck', 'Kitchen', 'Living room with fireplace', 'Dining area'],
    highlights: ['Entire house', '4 bed, 2 bath', 'Sleeps 8', '9.6 Rating', 'Pool', 'Pet Friendly'],
    petPolicy: 'Pet friendly - bring your furry friends',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 235,
    status: 'INACTIVE',
  },
  {
    id: 'gleneagles-4533',
    name: 'Uptown Place with Gated Yard',
    address: '4533 Gleneagles Dr',
    city: 'Midland',
    state: 'TX',
    zipCode: '79707',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 8,
    rating: 8.8,
    reviewCount: 20,
    vrboId: '4056016',
    vrboUrl: 'https://www.vrbo.com/4056016',
    amenities: ['Gated Yard', 'Covered Parking', 'Kitchen', 'Washer', 'Dryer', 'Air Conditioning', 'Free WiFi'],
    description: 'Uptown Place with gated yard. Currently has long-term renter — inactive on VRBO.',
    fullDescription: 'Uptown Place offers a secure gated yard and covered parking in a convenient Midland location. With 20 reviews and an 8.8 rating, guests love the peace of mind and comfort. Currently occupied by a long-term renter — check back soon for availability.',
    rooms: [
      { name: 'Bedroom 1', beds: '1 King Bed' },
      { name: 'Bedroom 2', beds: '1 Queen Bed' },
      { name: 'Bedroom 3', beds: '2 Twin Beds' },
    ],
    bathrooms_detail: [
      { name: 'Bathroom 1', features: 'Bathtub or shower · Toilet' },
      { name: 'Bathroom 2', features: 'Shower only · Toilet' },
    ],
    spaces: ['Gated yard', 'Covered parking', 'Kitchen', 'Living room', 'Dining area'],
    highlights: ['Entire house', '3 bed, 2 bath', 'Sleeps 8', 'Gated Yard', 'Covered Parking'],
    petPolicy: 'No pets allowed',
    checkInTime: '4:00 PM',
    checkOutTime: '11:00 AM',
    propertyType: 'HOUSE',
    nightlyRate: 195,
    status: 'INACTIVE',
  },
];

export function getPropertyById(id: string): PropertyListing | undefined {
  return PROPERTIES.find(p => p.id === id);
}

export function getPropertySlugs(): string[] {
  return PROPERTIES.map(p => p.id);
}
